### ISSUE TITLE
Extension hangs by uncaught exceptions from REST calls

### ISSUE THREAD

**Issue by sevillal** [microsoft/vscode-tools-for-ai#1040]
- tree hangs
- completions hangs

**Comment by sevillal** [comment]
Caused by https://github.com/microsoft/vscode-azure-account/issues/53

- Extension uses credential provided by Azure Account extension to authorize REST requests.
- Credentials follow ServiceClientCredentials interface, which contains a signRequest method which tries to get token from cache and set it in the Authorization header
- Azure Account still uses adal-node
- Token is somehow not found in cache and throws the "Entry not found in cache" error

**node_modules\ms-rest\lib\serviceClient.js**
responseBody error
`SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at <REDACTED>\node_modules\ms-rest\lib\serviceClient.js:56:1
    at retryCallback (<REDACTED>\node_modules\ms-rest\lib\filters\systemErrorRetryPolicyFilter.js:89:1)
    at retryCallback (<REDACTED>\node_modules\ms-rest\lib\filters\exponentialRetryPolicyFilter.js:140:1)
    at <REDACTED>\node_modules\ms-rest\lib\filters\rpRegistrationFilter.js:33:1
    at handleRedirect (<REDACTED>\node_modules\ms-rest\lib\filters\redirectFilter.js:39:1)
    at <REDACTED>\node_modules\ms-rest\lib\filters\formDataFilter.js:23:1
    at retryCallback (<REDACTED>\node_modules\ms-rest\lib\filters\systemErrorRetryPolicyFilter.js:89:1)
    at retryCallback (<REDACTED>\node_modules\ms-rest\lib\filters\exponentialRetryPolicyFilter.js:140:1)
    at <REDACTED>\node_modules\ms-rest\lib\filters\rpRegistrationFilter.js:33:1
    at handleRedirect (<REDACTED>\node_modules\ms-rest\lib\filters\redirectFilter.js:39:1)
    at <REDACTED>\node_modules\ms-rest\lib\filters\formDataFilter.js:23:1
    at <REDACTED>\node_modules\ms-rest\lib\filters\signingFilter.js:19:1
    at <REDACTED>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:246:72548
    at <REDACTED>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:246:72340
    at <REDACTED>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:211:78956
    at b.<anonymous> (<REDACTED>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:211:84264)
    at <REDACTED>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:211:78868
    at <REDACTED>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:211:55201
    at <REDACTED>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:211:53182
    at <REDACTED>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:211:52802
    at i.find (<REDACTED>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:211:63510)
    at <REDACTED>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:446:2637
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {vslsStack: Array(25), stack: 'SyntaxError: Unexpected token u in JSON at po…ctions (internal/process/task_queues.js:93:5)', message: 'Unexpected token u in JSON at position 0'}`

err content:
`Error: Entry not found in cache.
    at s.createError (<REDACTED>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:211:62938)
    at b.<anonymous> (<REDACTED>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:211:84273)
    at <REDACTED>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:211:78868
    at <REDACTED>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:211:55201
    at <REDACTED>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:211:53182
    at <REDACTED>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:211:52802
    at i.find (<REDACTED>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:211:63510)
    at <REDACTED>\.vscode\extensions\ms-vscode.azure-account-0.9.8\dist\extension.js:446:2637
    at runMicrotasks (<anonymous>)
    at runNextTicks (internal/process/task_queues.js:58:5)
    at processTimers (internal/timers.js:494:9) {vslsStack: Array(11), stack: 'Error: Entry not found in cache.
    at s.cre…  at processTimers (internal/timers.js:494:9)', message: 'Entry not found in cache.'}`

**Comment by SiddhanthUnnithan** [comment]
Follow-up: @sevillal link the msal upgrade issue here. See if we can follow up with the Az Account extension team to see whether work is planned.

**Comment by sevillal** [comment]
msal upgrade issue: https://github.com/microsoft/vscode-azure-account/issues/203

**Comment by csiebler** [comment]
Btw, this also seems to happen when I leave the VSCode window open for a while, and then try to do a "Create Job" command with the new CLI from within VSCode. The "checking workspace" window will hang forver:

![image](https://user-images.githubusercontent.com/525867/122194547-d5f53d00-ce95-11eb-9144-88ca3ffd9975.png)

Thanks
Clemens

**Comment by SiddhanthUnnithan** [comment]
Hypothesis: caused by the Azure account extension because they're using adal. Think that moving to msal will fix.

Follow up with someone else on the Azure account team with the issue.

**Comment by SiddhanthUnnithan** [comment]
Relevant issue that the CA team was running into: https://msdata.visualstudio.com/Vienna/_workitems/edit/1256168

**Comment by SiddhanthUnnithan** [comment]
Stop-gap: The extension knows when the call is stuck, pop open a notification to the user prompting them to reload their window.

All extensions that rely on the Azure Account extension experience this problem. All of them show a toast notification with the reload prompt. We want to follow that same pattern.
