### ISSUE TITLE
Connection Error requests.exceptions.ConnectionError

### ISSUE THREAD

**Issue by rajaasokan** [microsoft/vscode-tools-for-ai#1611]
Does this occur consistently?  Yes
Repro steps:

1. Submit the job from local to remote AzureML workspace

Action: azureml.commandPalette.workspace.setDefault
Error type: ECONNRESET
Error Message: request to redacted:url failed, reason: read ECONNRESET

Version: 0.14.0
OS: darwin
OS Release: 21.5.0
Product: Visual Studio Code
Product Version: 1.69.0
Language: en

<details>
Not able to authenticate to Azure ML
<summary>Call Stack</summary>
Getting workspace and compute target...
Warning: Falling back to use azure cli login credentials.
If you run your code in unattended mode, i.e., where you can't give a user input, then we recommend to use ServicePrincipalAuthentication or MsiAuthentication.
Please refer to aka.ms/aml-notebook-auth for different authentication mechanisms in azureml-sdk.
Traceback (most recent call last):
  File "/Users/raja/dev/video/lnd037_video_analytics_land/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/raja/dev/video/lnd037_video_analytics_land/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/Users/raja/dev/video/lnd037_video_analytics_land/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/Users/raja/dev/video/lnd037_video_analytics_land/venv/lib/python3.8/site-packages/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/Users/raja/dev/video/lnd037_video_analytics_land/venv/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/Users/raja/dev/video/lnd037_video_analytics_land/venv/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/Users/raja/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/Users/raja/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/Users/raja/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 54] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/raja/dev/video/lnd037_video_analytics_land/venv/lib/python3.8/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/Users/raja/dev/video/lnd037_video_analytics_land/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/Users/raja/dev/video/lnd037_video_analytics_land/venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/raja/dev/video/lnd037_video_analytics_land/venv/lib/python3.8/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/Users/raja/dev/video/lnd037_video_analytics_land/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/raja/dev/video/lnd037_video_analytics_land/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/Users/raja/dev/video/lnd037_video_analytics_land/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/Users/raja/dev/video/lnd037_video_analytics_land/venv/lib/python3.8/site-packages/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/Users/raja/dev/video/lnd037_video_analytics_land/venv/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/Users/raja/dev/video/lnd037_video_analytics_land/venv/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/Users/raja/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/Users/raja/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/Users/raja/.pyenv/versions/3.8.5/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pipelines/setup_mlops.py", line 60, in <module>
    compute_target_name = ComputeTarget(workspace=workspace, name=cluster_name)
  File "/Users/raja/dev/video/lnd037_video_analytics_land/venv/lib/python3.8/site-packages/azureml/core/compute/compute.py", line 71, in __new__
    compute_payload = cls._get(workspace, name)
  File "/Users/raja/dev/video/lnd037_video_analytics_land/venv/lib/python3.8/site-packages/azureml/core/compute/compute.py", line 277, in _get
    resp = ClientBase._execute_func(get_requests_session().get, endpoint, params=params, headers=headers)
  File "/Users/raja/dev/video/lnd037_video_analytics_land/venv/lib/python3.8/site-packages/azureml/_restclient/clientbase.py", line 374, in _execute_func
    return cls._execute_func_internal(
  File "/Users/raja/dev/video/lnd037_video_analytics_land/venv/lib/python3.8/site-packages/azureml/_restclient/clientbase.py", line 367, in _execute_func_internal
    left_retry = cls._handle_retry(back_off, left_retry, total_retry, error, logger, func)
  File "/Users/raja/dev/video/lnd037_video_analytics_land/venv/lib/python3.8/site-packages/azureml/_restclient/clientbase.py", line 399, in _handle_retry
    raise error
  File "/Users/raja/dev/video/lnd037_video_analytics_land/venv/lib/python3.8/site-packages/azureml/_restclient/clientbase.py", line 358, in _execute_func_internal
    response = func(*args, **kwargs)
  File "/Users/raja/dev/video/lnd037_video_analytics_land/venv/lib/python3.8/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/Users/raja/dev/video/lnd037_video_analytics_land/venv/lib/python3.8/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/raja/dev/video/lnd037_video_analytics_land/venv/lib/python3.8/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/Users/raja/dev/video/lnd037_video_analytics_land/venv/lib/python3.8/site-packages/requests/adapters.py", line 547, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))

```
ClientRequest.<anonymous> extension.js:2:62002
```

</details>

**Comment by tbombach** [comment]
Hi @rajaasokan, thank you for reporting this. My apologies for this issue and we'll try to get to the bottom of this. Do you have any network configuration that affects requests to the Azure ML service? For example, do you access your workspace with a private endpoint in a virtual network? Are you able to access the Azure ML portal at https://ml.azure.com ?

**Comment by shsuman** [comment]
Closing because of inactivity. Please reopen if need be :)
