### ISSUE TITLE
Cannot connect to any compute instance after password change. "Password is required." Error message

### ISSUE THREAD

**Issue by h-mattos** [microsoft/vscode-tools-for-ai#1616]
Does this occur consistently? Yes
Repro steps:

1. Change account password
2. Try to connect from VS Code to a compute instance
3. Log in when asked with default browser (Chrome)
4. Close browser when prompted
5. Fail to connect with error message "Password is required." even though password was given when log in was required. (Obviously, the expected behavior is to be able to remote connect to any of my compute instances)

PS. I am able to see, start and stop compute instances, but not connect to any. Tried logging out and back in (in the browser and from the extension shortcut "Azure: Sign out". Tried clean reinstalling VS Code and extensions to no avail. Tried with different subscriptions and workspaces, none work. These messages appear on the bottom right corner:

<img width="465" alt="image" src="https://user-images.githubusercontent.com/39918825/179934395-e49f5d54-b9f7-41c4-b090-e769c739b528.png">

Action: azureml.viewContext.computeInstance.connect
Error type: Error
Error Message: Password required.

Version: 0.14.0
OS: darwin
OS Release: 22.0.0
Product: Visual Studio Code
Product Version: 1.69.2
Language: en

**Comment by shsuman** [comment]
@h-mattos Apologies that you are facing this issue.

Can you please share the **Trace** logs with us ? 

You can enable **Trace** logging by changing the user setting azureML - Remote.logging.level to **trace**

![image](https://user-images.githubusercontent.com/44413557/161809386-9dd36d4e-3a50-4b01-98e0-72cf977c09cb.png)

Then just try to make a remote connection in the VSCode window and after it fails, open the output channel (Ctrl + Shift + U or View -> Output), and select the **Azure ML - Remote** output:

![image](https://user-images.githubusercontent.com/44413557/161811181-abc0a190-a968-4955-8d5b-e41923898c30.png)

**Comment by h-mattos** [comment]
@shsuman Thank you very much for the prompt response. Of course, but there is not anything new in the AzureML - Remote logs:
```
[Trace - 2022-07-20 14:21:31.313] Resolver.getResolverProtocol called with arguments: []
[Error - 2022-07-20 14:22:26.100] Error: Password is required.
```

The following log is for AzureML extension:
```
[Debug - 2022-07-20 14:21:31.488] Registering Compute instance remote server provider
[Debug - 2022-07-20 14:21:31.488] Ensuring Jupyter extension is installed
[Debug - 2022-07-20 14:21:31.488] Jupyter extension is already installed
[Error - 2022-07-20 14:21:32.211] Error: Unknown Error retrieving susbcriptions from Azure Account extension
[Error - 2022-07-20 14:22:00.739] Error: Operation cancelled.
	at n.<anonymous> (/Users/hmattos/.vscode/extensions/ms-toolsai.vscode-ai-0.14.0/dist/src/extension.js:2:2065972)
	at Generator.next (<anonymous>)
	at s (/Users/hmattos/.vscode/extensions/ms-toolsai.vscode-ai-0.14.0/dist/src/extension.js:2:2065401)
	at processTicksAndRejections (node:internal/process/task_queues:96:5) []
[Error - 2022-07-20 14:22:00.740] Error: Operation cancelled.
	at n.<anonymous> (/Users/hmattos/.vscode/extensions/ms-toolsai.vscode-ai-0.14.0/dist/src/extension.js:2:2065972)
	at Generator.next (<anonymous>)
	at s (/Users/hmattos/.vscode/extensions/ms-toolsai.vscode-ai-0.14.0/dist/src/extension.js:2:2065401)
	at processTicksAndRejections (node:internal/process/task_queues:96:5) []
[Error - 2022-07-20 14:22:00.740] Error: Operation cancelled.
	at n.<anonymous> (/Users/hmattos/.vscode/extensions/ms-toolsai.vscode-ai-0.14.0/dist/src/extension.js:2:2065972)
	at Generator.next (<anonymous>)
	at s (/Users/hmattos/.vscode/extensions/ms-toolsai.vscode-ai-0.14.0/dist/src/extension.js:2:2065401)
	at processTicksAndRejections (node:internal/process/task_queues:96:5) []
[Error - 2022-07-20 14:22:00.740] Operation cancelled.
[Error - 2022-07-20 14:22:00.740] Error: Operation cancelled.
	at n.<anonymous> (/Users/hmattos/.vscode/extensions/ms-toolsai.vscode-ai-0.14.0/dist/src/extension.js:2:2065972)
	at Generator.next (<anonymous>)
	at s (/Users/hmattos/.vscode/extensions/ms-toolsai.vscode-ai-0.14.0/dist/src/extension.js:2:2065401)
	at processTicksAndRejections (node:internal/process/task_queues:96:5) []
[Debug - 2022-07-20 14:22:12.946] Telemetry Event: subscription/getChildren/info Measures: undefined Props: {
    "numberOfWorkspaces": "1",
    "subscriptionId": [Redacted]
}
[Error - 2022-07-20 14:22:25.462] Error: Operation cancelled.
	at n.<anonymous> (/Users/hmattos/.vscode/extensions/ms-toolsai.vscode-ai-0.14.0/dist/src/extension.js:2:2065972)
	at Generator.next (<anonymous>)
	at s (/Users/hmattos/.vscode/extensions/ms-toolsai.vscode-ai-0.14.0/dist/src/extension.js:2:2065401)
	at processTicksAndRejections (node:internal/process/task_queues:96:5) []
[Debug - 2022-07-20 14:22:25.463] Ensuring that Compute instance hmattos-md is running
[Debug - 2022-07-20 14:22:25.463] Compute instance hmattos-md is already running
[Info - 2022-07-20 14:22:25.465] Compute instance to connect to: https://hmattos-md.eastus2.instances.azureml.ms/
[Error - 2022-07-20 14:22:26.104] Error: Password is required.
```

You are right, I can start and stop instances (though, every time I open VS Code, it asks for log in, which is unusual). On the other hand, in my other computer I can connect normally.

**Comment by shsuman** [comment]
@h-mattos Can you please try to open the Azure Tree view (Shift +Alt + A) from the activity bar and see if you can see list of your subscriptions ?

![image](https://user-images.githubusercontent.com/44413557/180010568-0ead4501-5cd7-4fe5-ab68-d133ad3c5bf0.png)

If it fails, can you install Azure Resources extension and see if you can list the subscriptions in tree view for them ?

The thing is, I am trying to determine whether this is a general error in Azure Account or something specific to Azure ML.

**Comment by h-mattos** [comment]
> @h-mattos Can you please try to open the Azure Tree view (Shift +Alt + A) from the activity bar on your local VSCode instance and see if you can see list of your subscriptions ?
> 
> ![image](https://user-images.githubusercontent.com/44413557/180010568-0ead4501-5cd7-4fe5-ab68-d133ad3c5bf0.png)
> 
> If it fails, can you install Azure Resources extension and see if you can list the subscriptions in tree view for them ?
> 
> The thing is, I am trying to determine whether this is a general error in Azure Account or something specific to Azure ML.

Yes, I can list all of my subscriptions, workspaces within, etc., thats how I am starting/stopping instances.

**Comment by shsuman** [comment]
@h-mattos I tried to repro the problem on my personal account but couldn't. Would you be free for a quick call, so I can closely look into the issue ? I am available anytime before PST noon Monday to Friday.

**Comment by shsuman** [comment]
Closing because of inactivity. Please reopen if need be :)
