### ISSUE TITLE
Cannot connect VSCode to remote Compute instance

### ISSUE THREAD

**Issue by ouaretf** [microsoft/vscode-tools-for-ai#1746]
## Expected Behavior
Cannot connect VSCode to remote Compute instance

## Steps to Reproduce the Problem

  1. Create new compute instance
  2. Use Azure Machine Learning Extension on the VS code
  3. Browse to the compute instance
  4. Trigger connection (right click on the compute instance)
Getting following error:
[Error - 2022-10-06 09:54:17.473] TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    |     property 'ui' -> object with constructor 't.AzExtUserInput'
    --- property '_context' closes the circle
	at JSON.stringify (<anonymous>)
	at c:\Users\faycalouaret\.vscode\extensions\ms-toolsai.vscode-ai-remote-0.18.1\dist\src\extension.js:2:1907064
	at Array.map (<anonymous>)
	at t.Logger.format (c:\Users\faycalouaret\.vscode\extensions\ms-toolsai.vscode-ai-remote-0.18.1\dist\src\extension.js:2:1907017)
	at t.Logger.trace (c:\Users\faycalouaret\.vscode\extensions\ms-toolsai.vscode-ai-remote-0.18.1\dist\src\extension.js:2:1906916)
	at o.value (c:\Users\faycalouaret\.vscode\extensions\ms-toolsai.vscode-ai-remote-0.18.1\dist\src\extension.js:2:1908306)
	at c:\Users\faycalouaret\.vscode\extensions\ms-toolsai.vscode-ai-remote-0.18.1\dist\src\extension.js:2:1952982
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5) []
[Error - 2022-10-06 09:54:17.476] TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    |     property 'ui' -> object with constructor 't.AzExtUserInput'
    --- property '_context' closes the circle
	at JSON.stringify (<anonymous>)
	at c:\Users\faycalouaret\.vscode\extensions\ms-toolsai.vscode-ai-remote-0.18.1\dist\src\extension.js:2:1907064
	at Array.map (<anonymous>)
	at t.Logger.format (c:\Users\faycalouaret\.vscode\extensions\ms-toolsai.vscode-ai-remote-0.18.1\dist\src\extension.js:2:1907017)
	at t.Logger.trace (c:\Users\faycalouaret\.vscode\extensions\ms-toolsai.vscode-ai-remote-0.18.1\dist\src\extension.js:2:1906916)
	at o.value (c:\Users\faycalouaret\.vscode\extensions\ms-toolsai.vscode-ai-remote-0.18.1\dist\src\extension.js:2:1908306)
	at C.setupRemoteDependencies (c:\Users\faycalouaret\.vscode\extensions\ms-toolsai.vscode-ai-remote-0.18.1\dist\src\extension.js:2:1956483)
	at o.value (c:\Users\faycalouaret\.vscode\extensions\ms-toolsai.vscode-ai-remote-0.18.1\dist\src\extension.js:2:1908347)
	at c:\Users\faycalouaret\.vscode\extensions\ms-toolsai.vscode-ai-remote-0.18.1\dist\src\extension.js:2:1952982
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5) []
[Info - 2022-10-06 09:54:17.482] Using commit id "74b1f979648cc44d385a2286793c226e611f59e7" and quality "stable" for server

Additional information
Using Terminal from the ML workspace:
It seems the connection to internet is not allowed from the compute. 
It tries to install the vscode server part:
ps -elf | grep wget
0 S azureus+ 2002008 2002007  0  80   0 -  3603 hrtime 07:47 pts/0    00:00:00 wget --connect-timeout=7 --dns-timeout=7 -nv -O vscode-server.tar.gz https://update.code.visualstudio.com/commit:74b1f979648cc44d385a2286793c226e611f59

curl -v https://update.code.visualstudio.com/commit:74b1f979648cc44d385a2286793c226e611f59
*   Trying 51.144.164.215:443...

## Specifications
  - VS Code Version: 1.71.2
  - Platform: Win11

**Comment by tbombach** [comment]
Hi @ouaretf, I'm sorry you are encountering this issue. Thank you for providing information to help us try to figure out what is going wrong. Is your workspace secured in a virtual network? If so, it will need to be configured to allow traffic to VS Code hosts to set up the remote connection. Here is a document with instructions: https://learn.microsoft.com/en-us/azure/machine-learning/how-to-access-azureml-behind-firewall?tabs=ipaddress%2Cpublic#required-public-internet-access

**Comment by TaoufikAITALLA** [comment]
Hello @tbombach,

i'm facing the same problem @ouaretf , I've secured ML and also it related resources using private endpoint. 
On NSG i've added all required inbound and outbound rules but it seems not resolving the problem.
The Dns resolution is ok but access to resorce through http
Thank you

**Comment by TaoufikAITALLA** [comment]
Hello @tbombach 
I've managed to find the solution, ML compute with "No public Ip" will not allow outbound internet access unless it's connected to NAT device such as Firewall or NVA.
the solution is described: https://learn.microsoft.com/en-us/azure/batch/batch-pool-no-public-ip-address?source=recommendations#outbound-access-to-the-internet

**Comment by shsuman** [comment]
Closing because of inactivity. Please reopen if need be :)
