### ISSUE TITLE
Extension initialization fails if the active python interpreter is 3.7+

### ISSUE THREAD

**Issue by greazer** [Microsoft/vscode-tools-for-ai#177]

**Comment by greazer** [comment]
When trying on my home system I got this stacktrace when trying to start the flask server.

Flask Error: Error: Command failed: c:\Users\Jim\.azureml\envs\amlsdk\Scripts\python.exe d:\Users\Jim\Repos\OpenMindVSCode\FlaskServers\amlflask\server.py -p 6871 -s None
Traceback (most recent call last):
  File "d:\Users\Jim\Repos\OpenMindVSCode\FlaskServers\amlflask\server.py", line 29, in <module>
    from amlflask.common.utils import EPRINT,DEBUG, extract_from_compute_uri, get_auth_token, extract_from_workspace_uri
  File "d:\Users\Jim\Repos\OpenMindVSCode\FlaskServers\amlflask\common\utils.py", line 8, in <module>
    from azureml.core.authentication import ArmTokenAuthentication
  File "c:\Users\Jim\.azureml\envs\amlsdk\lib\site-packages\azureml\core\__init__.py", line 10, in <module>
    from azureml.core.workspace import Workspace
  File "c:\Users\Jim\.azureml\envs\amlsdk\lib\site-packages\azureml\core\workspace.py", line 21, in <module>
    from azureml._project import _commands
  File "c:\Users\Jim\.azureml\envs\amlsdk\lib\site-packages\azureml\_project\_commands.py", line 8, in <module>
    from azureml._base_sdk_common.common import create_role_assignment
  File "c:\Users\Jim\.azureml\envs\amlsdk\lib\site-packages\azureml\_base_sdk_common\common.py", line 25, in <module>
    from azureml._vendor.azure_cli_core._profile import Profile
  File "c:\Users\Jim\.azureml\envs\amlsdk\lib\site-packages\azureml\_vendor\azure_cli_core\_profile.py", line 33, in <module>
    from OpenSSL.crypto import load_certificate, FILETYPE_PEM
  File "c:\Users\Jim\.azureml\envs\amlsdk\lib\site-packages\OpenSSL\__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "c:\Users\Jim\.azureml\envs\amlsdk\lib\site-packages\OpenSSL\crypto.py", line 12, in <module>
    from cryptography import x509
  File "c:\Users\Jim\.azureml\envs\amlsdk\lib\site-packages\cryptography\x509\__init__.py", line 8, in <module>
    from cryptography.x509.base import (
  File "c:\Users\Jim\.azureml\envs\amlsdk\lib\site-packages\cryptography\x509\base.py", line 16, in <module>
    from cryptography.x509.extensions import Extension, ExtensionType
  File "c:\Users\Jim\.azureml\envs\amlsdk\lib\site-packages\cryptography\x509\extensions.py", line 18, in <module>
    from cryptography.hazmat.primitives import constant_time, serialization
  File "c:\Users\Jim\.azureml\envs\amlsdk\lib\site-packages\cryptography\hazmat\primitives\constant_time.py", line 11, in <module>
    from cryptography.hazmat.bindings._constant_time import lib
ModuleNotFoundError: No module named 'cryptography.hazmat.bindings._constant_time'

**Comment by greazer** [comment]
Not sure that this is an actual bug. Need to retry.

**Comment by greazer** [comment]
@shsuman, please validate this behavior. Do we work with python 3.7 or not?

**Comment by greazer** [comment]
Dupe of #79, which Xiaoyun indicated does not affect the extension.
