### ISSUE TITLE
When executing YAML, Azure CLI is not signed in and the login command recommended does not work

### ISSUE THREAD

**Issue by sevillal** [microsoft/vscode-tools-for-ai#1904]
1. Execute YAML to create compute
```(azureml_py38) azureuser@<ci-name>:~/cloudfiles/code$ az ml compute create --file "/home/azureuser/cloudfiles/code/Users/<user-id>/compute.yml"
Auto upgrade failed. name 'exit_code' is not defined
Traceback (most recent call last):
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/extensions/ml/azext_mlv2/manual/custom/compute.py", line 140, in ml_compute_create
    log_and_raise_error(e, debug)
  File "/opt/az/extensions/ml/azext_mlv2/manual/custom/raise_error.py", line 117, in log_and_raise_error
    raise cli_error
  File "/opt/az/extensions/ml/azext_mlv2/manual/custom/compute.py", line 137, in ml_compute_create
    compute = ml_client.begin_create_or_update(compute, no_wait=no_wait)
  File "/opt/az/extensions/ml/azext_mlv2/manual/vendored_curated_sdk/azure/ai/ml/_ml_client.py", line 590, in begin_create_or_update
    return _begin_create_or_update(entity, self._operation_container.all_operations, **kwargs)
  File "/anaconda/envs/azureml_py38/lib/python3.8/functools.py", line 875, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/opt/az/extensions/ml/azext_mlv2/manual/vendored_curated_sdk/azure/ai/ml/_ml_client.py", line 654, in _
    return operations[AzureMLResourceType.COMPUTE].begin_create_or_update(entity, **kwargs)
  File "/opt/az/extensions/ml/azext_mlv2/manual/vendored_curated_sdk/azure/ai/ml/_telemetry/activity.py", line 169, in wrapper
    return f(*args, **kwargs)
  File "/opt/az/extensions/ml/azext_mlv2/manual/vendored_curated_sdk/azure/ai/ml/operations/_compute_operations.py", line 112, in begin_create_or_update
    compute.location = self._get_workspace_location()
  File "/opt/az/extensions/ml/azext_mlv2/manual/vendored_curated_sdk/azure/ai/ml/operations/_compute_operations.py", line 303, in _get_workspace_location
    workspace = self._workspace_operations.get(self._resource_group_name, self._workspace_name)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/opt/az/extensions/ml/azext_mlv2/manual/vendored_curated_sdk/azure/ai/ml/_restclient/v2022_01_01_preview/operations/_workspaces_operations.py", line 617, in get
    raise HttpResponseError(response=response, model=error, error_format=ARMErrorFormat)
azure.core.exceptions.HttpResponseError: (AuthorizationFailed) The client '<user-id>@microsoft.com' with object id 'dd62b32b-e14a-4562-a176-00121422e952' does not have authorization to perform action 'Microsoft.MachineLearningServices/workspaces/read' over scope '/subscriptions/<subscription>/resourceGroups/<rg>/providers/Microsoft.MachineLearningServices/workspaces/<workspace>' or the scope is invalid. If access was recently granted, please refresh your credentials.
Code: AuthorizationFailed
Message: The client '<user-id>@microsoft.com' with object id '<user-object-id>' does not have authorization to perform action 'Microsoft.MachineLearningServices/workspaces/read' over scope '/subscriptions/<subscription>/resourceGroups/<rg>/providers/Microsoft.MachineLearningServices/workspaces/<workspace>' or the scope is invalid. If access was recently granted, please refresh your credentials.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/anaconda/envs/azureml_py38/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/anaconda/envs/azureml_py38/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/cli/__main__.py", line 49, in <module>
    exit_code = cli_main(az_cli, sys.argv[1:])
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/cli/__main__.py", line 36, in cli_main
    return cli.invoke(args)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/knack/cli.py", line 245, in invoke
    exit_code = self.exception_handler(ex)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/cli/core/__init__.py", line 127, in exception_handler
    return handle_exception(ex)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/cli/core/util.py", line 65, in handle_exception
    from msal_extensions.persistence import PersistenceError
ImportError: cannot import name 'PersistenceError' from 'msal_extensions.persistence' (/anaconda/envs/azureml_py38/lib/python3.8/site-packages/msal_extensions/persistence.py)
```

2. Running `az login --identity` does not work.
3. After restarting the compute instance it worked fine

**Comment by sevillal** [comment]
Seems to be related with: https://github.com/microsoft/vscode-tools-for-ai/issues/1836

**Comment by tbombach** [comment]
Closing this and tracking progress with: https://github.com/microsoft/vscode-tools-for-ai/issues/1836
