### ISSUE TITLE
Forbidden error from Azure ML extension remotely connected to CI in VS Code Web

### ISSUE THREAD

**Issue by lebaro-msft** [microsoft/vscode-tools-for-ai#2038]
Does this occur consistently? Doesn't seem like it
Repro steps:
Unclear - couldn't see any blocking side effects of the error. Happens as soon as I launched VS Code for the Web remotely connected to Compute Instance

Action: azureAccount.onSessionsChanged
Error type: 403
Error Message: Forbidden

Version: 0.30.3
OS: linux
OS Release: 5.15.0-1035-azure
Product: Visual Studio Code
Product Version: 1.78.1
Language: en

<details>
<summary>Call Stack</summary>

```
t.createAzureMLHttpError extension.js:2:2000471
t.HttpService.<anonymous> extension.js:2:2003174
s extension.js:2:2000695
```

</details>

**Comment by sevillal** [comment]
![image](https://github.com/microsoft/vscode-tools-for-ai/assets/56176070/711c100d-1f15-4253-873d-800414729fa5)

```
[Info - 2023-05-11 00:19:01.871] Using ConnectedComputeInstanceJupyterUriProvider [Error - 2023-05-11 00:19:06.799] Error: Forbidden [Error - 2023-05-11 00:19:06.800] ForbiddenError: Forbidden at t.createAzureMLHttpError (/home/azureuser/.vscode-server/extensions/ms-toolsai.vscode-ai-0.32.2/dist/src/extension.js:2:2251299) at t.HttpService.<anonymous> (/home/azureuser/.vscode-server/extensions/ms-toolsai.vscode-ai-0.32.2/dist/src/extension.js:2:2254002) at Generator.next (<anonymous>) at s (/home/azureuser/.vscode-server/extensions/ms-toolsai.vscode-ai-0.32.2/dist/src/extension.js:2:2251523) at processTicksAndRejections (node:internal/process/task_queues:96:5) [] [Error - 2023-05-11 00:19:10.008] Forbidden [Error - 2023-05-11 00:19:10.008] ForbiddenError: Forbidden at t.createAzureMLHttpError (/home/azureuser/.vscode-server/extensions/ms-toolsai.vscode-ai-0.32.2/dist/src/extension.js:2:2251299) at t.HttpService.<anonymous> (/home/azureuser/.vscode-server/extensions/ms-toolsai.vscode-ai-0.32.2/dist/src/extension.js:2:2254002) at Generator.next (<anonymous>) at s (/home/azureuser/.vscode-server/extensions/ms-toolsai.vscode-ai-0.32.2/dist/src/extension.js:2:2251523) at processTicksAndRejections (node:internal/process/task_queues:96:5) []
```

**Comment by shsuman** [comment]
@sevillal Is there any update here or should we close this ?

**Comment by sevillal** [comment]
Closing as we are unable to repro anymore.
