### ISSUE TITLE
Errors when trying to edit compute target 

### ISSUE THREAD

**Issue by swinner95** [Microsoft/vscode-tools-for-ai#207]
When I nagivated to the Azure extension and selected to edit my compute target, I got the errors below: 

Error message #1:
Cannot set property 'status' of undefined

Error nessage #2:
AMLFlask:
Traceback (most recent call last):
  File "c:\Users\shwinne\.azureml\envs\amlsdk\lib\site-packages\azureml\core\compute\compute.py", line 342, in list
    resp.raise_for_status()
  File "c:\Users\shwinne\.azureml\envs\amlsdk\lib\site-packages\requests\models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://management.azure.com/subscriptions/15ae9cb6-95c1-483d-a0e3-b1a1a3b06324/resourceGroups/shwinner/providers/Microsoft.MachineLearningServices/workspaces/pipelinesnotebook/computes?api-version=2018-11-19

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\shwinne\.vscode\extensions\ms-toolsai.vscode-ai-0.4.5\FlaskServers\amlflask\common\decorator.py", line 26, in wrapper
    return function(*args, **kwargs)
  File "c:\Users\shwinne\.vscode\extensions\ms-toolsai.vscode-ai-0.4.5\FlaskServers\amlflask\controller\compute.py", line 226, in get_compute
    computes = _list_compute(get_auth_token(),subscription_id,resource_group,workspace_name)
  File "c:\Users\shwinne\.vscode\extensions\ms-toolsai.vscode-ai-0.4.5\FlaskServers\amlflask\controller\compute.py", line 304, in _list_compute
    return ws.compute_targets
  File "c:\Users\shwinne\.azureml\envs\amlsdk\lib\site-packages\azureml\core\workspace.py", line 810, in compute_targets
    return {compute_target.name: compute_target for compute_target in ComputeTarget.list(self)}
  File "c:\Users\shwinne\.azureml\envs\amlsdk\lib\site-packages\azureml\core\compute\compute.py", line 347, in list
    'Content: {}'.format(resp.status_code, resp.headers, resp.content))
azureml.exceptions._azureml_exception.ComputeTargetException: Error occurred retrieving targets:
Response Code: 401
Headers: {'Cache-Control': 'no-cache', 'Pragma': 'no-cache', 'Content-Type': 'application/json; charset=utf-8', 'Expires': '-1', 'WWW-Authenticate': 'Bearer authorization_uri="https://login.windows.net/72f988bf-86f1-41af-91ab-2d7cd011db47", error="invalid_token", error_description="The access token has expired."', 'x-ms-failure-cause': 'gateway', 'x-ms-request-id': 'e7e86377-417e-4e1b-88d2-afc93495e0a9', 'x-ms-correlation-request-id': 'e7e86377-417e-4e1b-88d2-afc93495e0a9', 'x-ms-routing-request-id': 'WESTUS2:20190318T222922Z:e7e86377-417e-4e1b-88d2-afc93495e0a9', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'X-Content-Type-Options': 'nosniff', 'Date': 'Mon, 18 Mar 2019 22:29:22 GMT', 'Connection': 'close', 'Content-Length': '173'}
Content: b'{"error":{"code":"ExpiredAuthenticationToken","message":"The access token expiry UTC time \'3/18/2019 8:46:52 PM\' is earlier than current UTC time \'3/18/2019 10:29:22 PM\'."}}'

**Comment by greazer** [comment]
Reload VSCode. That should resolve the problem. We have fixed this per #204.

**Comment by swinner95** [comment]
I think we should put a notification/message for users who would experience similar problems so that they are aware to reload VSCode to resolve the issue. Or can we reload VSCode on behalf of the user?

**Comment by greazer** [comment]
Well, I don't think we want to reload automatically. The problem should no longer occur as it was caused due to caching workspace information on our side. We don't think we need that performance optimization at all, so by removing it, the potential for this timeout problem to occur goes away.
