### ISSUE TITLE
Errors when refreshing the TreeView 

### ISSUE THREAD

**Issue by swinner95** [Microsoft/vscode-tools-for-ai#208]
When I navigate to the extension and select the refresh button, I get the two errors below. I tried signing in again to my Azure subscription but I got the same error messages.  

Error #1:

AMLFlask:
Traceback (most recent call last):
  File "c:\Users\shwinne\.vscode\extensions\ms-toolsai.vscode-ai-0.4.5\FlaskServers\amlflask\common\decorator.py", line 26, in wrapper
    return function(*args, **kwargs)
  File "c:\Users\shwinne\.vscode\extensions\ms-toolsai.vscode-ai-0.4.5\FlaskServers\amlflask\controller\pipeline.py", line 29, in list_pipeline
    pipelines = PublishedPipeline.get_all(ws)
  File "c:\Users\shwinne\.azureml\envs\amlsdk\lib\site-packages\azureml\pipeline\core\graph.py", line 3272, in get_all
    return graph_context.workflow_provider.published_pipeline_provider.get_all(active_only=active_only)
  File "c:\Users\shwinne\.azureml\envs\amlsdk\lib\site-packages\azureml\pipeline\core\_aeva_provider.py", line 1032, in get_all
    entities = self._service_caller.get_all_published_pipelines(active_only=active_only)
  File "c:\Users\shwinne\.azureml\envs\amlsdk\lib\site-packages\azureml\pipeline\core\_restclients\aeva\service_caller.py", line 566, in get_all_published_pipelines
    active_only=active_only)
  File "c:\Users\shwinne\.azureml\envs\amlsdk\lib\site-packages\azureml\pipeline\core\_restclients\aeva\aml_pipelines_api10.py", line 3347, in api_v10_subscriptions_by_subscription_id_resource_groups_by_resource_group_name_providers_microsoft_machine_learning_services_workspaces_by_workspace_name_pipelines_get
    raise ErrorResponseException(self._deserialize, response)
azureml.pipeline.core._restclients.aeva.models.error_response.ErrorResponseException: Operation returned an invalid status code 'Unauthorized'

Error # 2:

AMLFlask: Traceback (most recent call last): File "c:\Users\shwinne\.azureml\envs\amlsdk\lib\site-packages\azureml\core\compute\compute.py", line 342, in list resp.raise_for_status() File "c:\Users\shwinne\.azureml\envs\amlsdk\lib\site-packages\requests\models.py", line 940, in raise_for_status raise HTTPError(http_error_msg, response=self) requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://management.azure.com/subscriptions/15ae9cb6-95c1-483d-a0e3-b1a1a3b06324/resourceGroups/shwinner/providers/Microsoft.MachineLearningServices/workspaces/pipelinesnotebook/computes?api-version=2018-11-19 During handling of the above exception, another exception occurred: Traceback (most recent call last): File "c:\Users\shwinne\.vscode\extensions\ms-toolsai.vscode-ai-0.4.5\FlaskServers\amlflask\common\decorator.py", line 26, in wrapper return function(*args, **kwargs) File "c:\Users\shwinne\.vscode\extensions\ms-toolsai.vscode-ai-0.4.5\FlaskServers\amlf...

**Comment by greazer** [comment]
Very likely fixed by #204. Reload VSCode should workaround.
