### ISSUE TITLE
Error when clicking on the Compute Node if there were no previously created computes 

### ISSUE THREAD

**Issue by swinner95** [Microsoft/vscode-tools-for-ai#209]
When I simply click on a compute node and there are no computes created for that workspace, I get the error message below. Expectation: to see no artifact in the drop down list under compute  

Error Message: 
AMLFlask:
Traceback (most recent call last):
  File "c:\Users\shwinne\.vscode\extensions\ms-toolsai.vscode-ai-0.4.5\FlaskServers\amlflask\common\decorator.py", line 26, in wrapper
    return function(*args, **kwargs)
  File "c:\Users\shwinne\.vscode\extensions\ms-toolsai.vscode-ai-0.4.5\FlaskServers\amlflask\controller\compute.py", line 236, in list_compute
    computes = _list_compute(get_auth_token(),subscription_id,resource_group,workspace_name)
  File "c:\Users\shwinne\.vscode\extensions\ms-toolsai.vscode-ai-0.4.5\FlaskServers\amlflask\controller\compute.py", line 304, in _list_compute
    return ws.compute_targets
  File "c:\Users\shwinne\.azureml\envs\amlsdk\lib\site-packages\azureml\core\workspace.py", line 810, in compute_targets
    return {compute_target.name: compute_target for compute_target in ComputeTarget.list(self)}
  File "c:\Users\shwinne\.azureml\envs\amlsdk\lib\site-packages\azureml\core\compute\compute.py", line 366, in list
    env_obj = child.deserialize(workspace, env)
  File "c:\Users\shwinne\.azureml\envs\amlsdk\lib\site-packages\azureml\core\compute\amlcompute.py", line 453, in deserialize
    target._initialize(workspace, object_dict)
  File "c:\Users\shwinne\.azureml\envs\amlsdk\lib\site-packages\azureml\core\compute\amlcompute.py", line 76, in _initialize
    if provisioning_state in ["Succeeded", "Updating"] else None
  File "c:\Users\shwinne\.azureml\envs\amlsdk\lib\site-packages\azureml\core\compute\amlcompute.py", line 870, in deserialize
    if 'nodeStateCounts' in object_dict['properties'] else None
  File "c:\Users\shwinne\.azureml\envs\amlsdk\lib\site-packages\azureml\core\compute\amlcompute.py", line 949, in deserialize
    idle_node_count = object_dict['idleNodeCount'] if 'idleNodeCount' in object_dict else None
TypeError: argument of type 'NoneType' is not iterable

**Comment by swinner95** [comment]
I also get an error when I click on the Images or Deployment Node (if the drop down menu is empty for the Node)  


Error:

AMLFlask:
Traceback (most recent call last):
  File "c:\Users\shwinne\.azureml\envs\amlsdk\lib\site-packages\azureml\core\webservice\webservice.py", line 533, in list
    resp.raise_for_status()
  File "c:\Users\shwinne\.azureml\envs\amlsdk\lib\site-packages\requests\models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://eastus2.modelmanagement.azureml.net/api/subscriptions/15ae9cb6-95c1-483d-a0e3-b1a1a3b06324/resourceGroups/shwinner/providers/Microsoft.MachineLearningServices/workspaces/pipelines/services?api-version=2018-11-19&expand=true

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\shwinne\.vscode\extensions\ms-toolsai.vscode-ai-0.4.5\FlaskServers\amlflask\common\decorator.py", line 26, in wrapper
    return function(*args, **kwargs)
  File "c:\Users\shwinne\.vscode\extensions\ms-toolsai.vscode-ai-0.4.5\FlaskServers\amlflask\controller\service.py", line 142, in list_services
    services = Webservice.list(ws)
  File "c:\Users\shwinne\.azureml\envs\amlsdk\lib\site-packages\azureml\core\webservice\webservice.py", line 540, in list
    'Content: {}'.format(resp.status_code, resp.headers, resp.content))
azureml.exceptions._azureml_exception.WebserviceException: Received bad response from Model Management Service:
Response Code: 401
Headers: {'Date': 'Wed, 20 Mar 2019 18:07:23 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Strict-Transport-Security': 'max-age=15724800; includeSubDomains; preload'}
Content: b'{"code":"Unauthorized","statusCode":401,"message":"Unauthorized","details":[{"code":"InvalidOrExpiredToken","message":"The request token was either invalid or expired. Please try again with a valid token."}]}'

**Comment by greazer** [comment]
Very likely fixed by #204. Reload VSCode should workaround.
