### ISSUE TITLE
Error: command 'azureml.internal.activate' not found

### ISSUE THREAD

**Issue by DanielRejniak** [microsoft/vscode-tools-for-ai#2195]
## Expected Behavior

We have a workspace on Azure Machine Learning and are attempting to use the (web) or (desktop) VS Code editor to interact with the compute instance.

## Actual Behavior

When we try to access the (web) VS Code editor we can see the vs code server being downloaded and connection established then we also see an error that prevents us from getting any further.

It's worth mentioning that our Azure Machine Learning instance is behind the firewall and we followed the instructions [here](https://learn.microsoft.com/en-us/azure/machine-learning/how-to-access-azureml-behind-firewall?view=azureml-api-2&tabs=ipaddress%2Cpublic#scenario-visual-studio-code) to enable the required ports.

The error is : 
```
2023-10-11 14:06:14.889 [info] vscode-azureml-remote:web-socket-1: handshake request succeeded
2023-10-11 14:06:18.239 [error] Error: command 'azureml.internal.activate' not found
    at y.n (https://main.vscode-cdn.net/stable/e7e037083ff4455cf320e344325dacb480062c3c/out/vs/workbench/workbench.web.main.js:1554:12298)
    at y.executeCommand (https://main.vscode-cdn.net/stable/e7e037083ff4455cf320e344325dacb480062c3c/out/vs/workbench/workbench.web.main.js:1554:12227)
```

## Steps to Reproduce the Problem

  1. Open any Azure machine learning workspace.
  1. Pick a compute instance and select the (web) visual studio code option.
  1. Wait for the editor to span in a new window and observe the log with the error outlined above.

## Specifications

  - VS Code Version: Latest (Web Based)
  - Platform: Azure Machine Learning

**Comment by shsuman** [comment]
@DanielRejniak Thar error should not have any effect on your connection. Can you please provide us with the full Azure ML Remote - Web and vscode.dev logs to investigate what is going on ?

You can follow the steps mentioned [here](https://github.com/microsoft/vscode-tools-for-ai/wiki/FAQ#how-to-get-logs-for-azure-machine-learning---remote-web-connection-in-vs-code-web-vscodedev-)
