### ISSUE TITLE
Telemetry package error while making the remote connection

### ISSUE THREAD

**Issue by shsuman** [microsoft/vscode-tools-for-ai#2276]
```log
Error: Extension 'ms-toolsai.vscode-ai-remote' CANNOT use API proposal: telemetry.
Its package.json#enabledApiProposals-property declares: resolvers but NOT telemetry.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api ms-toolsai.vscode-ai-remote
	at v (c:\Users\shsuman\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:138:48007)
	at get telemetryConfiguration [as telemetryConfiguration] (c:\Users\shsuman\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:158:22070)
	at l (c:\Users\shsuman\.vscode\extensions\ms-toolsai.vscode-ai-remote-0.45.2024012309\dist\src\extension.js:2:721222)
	at l (c:\Users\shsuman\.vscode\extensions\ms-toolsai.vscode-ai-remote-0.45.2024012309\dist\src\extension.js:2:721219)
	at l (c:\Users\shsuman\.vscode\extensions\ms-toolsai.vscode-ai-remote-0.45.2024012309\dist\src\extension.js:2:721219)
	at l (c:\Users\shsuman\.vscode\extensions\ms-toolsai.vscode-ai-remote-0.45.2024012309\dist\src\extension.js:2:721138)
	at l (c:\Users\shsuman\.vscode\extensions\ms-toolsai.vscode-ai-remote-0.45.2024012309\dist\src\extension.js:2:721219)
	at l (c:\Users\shsuman\.vscode\extensions\ms-toolsai.vscode-ai-remote-0.45.2024012309\dist\src\extension.js:2:721219)
	at l (c:\Users\shsuman\.vscode\extensions\ms-toolsai.vscode-ai-remote-0.45.2024012309\dist\src\extension.js:2:721219)
	at l (c:\Users\shsuman\.vscode\extensions\ms-toolsai.vscode-ai-remote-0.45.2024012309\dist\src\extension.js:2:721219)
	at l (c:\Users\shsuman\.vscode\extensions\ms-toolsai.vscode-ai-remote-0.45.2024012309\dist\src\extension.js:2:721219)
	at l (c:\Users\shsuman\.vscode\extensions\ms-toolsai.vscode-ai-remote-0.45.2024012309\dist\src\extension.js:2:721138)
	at s (c:\Users\shsuman\.vscode\extensions\ms-toolsai.vscode-ai-remote-0.45.2024012309\dist\src\extension.js:2:720325)
	at c:\Users\shsuman\.vscode\extensions\ms-toolsai.vscode-ai-remote-0.45.2024012309\dist\src\extension.js:2:1528808
	at Array.map (<anonymous>)
	at t.Logger.format (c:\Users\shsuman\.vscode\extensions\ms-toolsai.vscode-ai-remote-0.45.2024012309\dist\src\extension.js:2:1528754)
	at t.Logger.trace (c:\Users\shsuman\.vscode\extensions\ms-toolsai.vscode-ai-remote-0.45.2024012309\dist\src\extension.js:2:1528653)
	at o.value (c:\Users\shsuman\.vscode\extensions\ms-toolsai.vscode-ai-remote-0.45.2024012309\dist\src\extension.js:2:1530041)
	at m.getRemoteTarget (c:\Users\shsuman\.vscode\extensions\ms-toolsai.vscode-ai-remote-0.45.2024012309\dist\src\extension.js:2:1559801)
	at c:\Users\shsuman\.vscode\extensions\ms-toolsai.vscode-ai-remote-0.45.2024012309\dist\src\extension.js:2:1617224
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5) []
```

**Comment by shsuman** [comment]
https://github.com/devdiv-microsoft/vscode-azureml-remote/pull/186
