### ISSUE TITLE
I am able to connect to VSCodeWebAPP in my internet explorer but opening VSCode desktop through Azure AML gives this error. 

### ISSUE THREAD

**Issue by usoni1** [microsoft/vscode-tools-for-ai#2341]
Does this occur consistently? 
Repro steps:

1.
2.

Action: Resolver.resolve
Error type: Y
Error Message: Connection is forbidden. Please make sure that you are logged in with the right Azure Account and the Remote target exists. (Error: Invalid response: 403 Forbidden)

Version: 0.48.0
OS: win32
OS Release: 10.0.22631
Product: Visual Studio Code
Product Version: 1.88.0
Language: en

<details>
<summary>Call Stack</summary>

```
Y.NotAvailable extensionHostProcess.js:150:8756
S.handle403Forbidden extension.js:2:1610594
S.handleError extension.js:2:1608251
o.value extension.js:2:1532093
extension.js:2:1624443extension.js:2:1624443
```

</details>

**Comment by shsuman** [comment]
@usoni1 Can you please provide me the logs by following the steps [here](https://github.com/microsoft/vscode-tools-for-ai/wiki/FAQ#how-to-get-trace-logs-for-azure-machine-learning---remote-extension-)

**Comment by shsuman** [comment]
Closing because of inactivity. Please reopen if need be :)

**Comment by usoni1** [comment]
[Trace - 2024-04-15 21:06:23.229] Resolver.getResolverProtocol called with arguments: []
[Debug - 2024-04-15 21:06:23.231] Registering Azure ML Uri Hanlder with path:  /computeInstance/remote
[Debug - 2024-04-15 21:06:23.231] Registering Azure ML Uri Hanlder with path:  /environmentContainer/remote
[Debug - 2024-04-15 21:06:23.231] Registering Azure ML Uri Hanlder with path:  /interactiveSession
[Debug - 2024-04-15 21:06:23.231] Registering Azure ML Uri Hanlder with path:  /interactiveSession/distributedJob
[Trace - 2024-04-15 21:06:23.341] Resolver.resolve called with arguments: [
    "amlext+2f737562736372697074696f6e732f38313031393064332d633737392d343736382d616665632d3363313538656339383533612f7265736f7572636547726f7570732f696875622d6c74632d6d6c2d7561742d72672f70726f7669646572732f4d6963726f736f66742e4d616368696e654c6561726e696e6753657276696365732f776f726b7370616365732f696875622d6c74632d7561742d6d6c2f636f6d70757465732f6c7463736f6e75746b613031",
    {
        "resolveAttempt": 1
    }
]
[Debug - 2024-04-15 21:06:23.345] Azure ML Remote resolver called for "/subscriptions/810190d3-c779-4768-afec-3c158ec9853a/resourceGroups/ihub-ltc-ml-uat-rg/providers/Microsoft.MachineLearningServices/workspaces/ihub-ltc-uat-ml/computes/ltcsonutka01", attempt 1
[Info - 2024-04-15 21:06:23.353] Remote session: {
    "telemetryProperties": {
        "isActivationEvent": "false",
        "lastStep": "",
        "result": "Succeeded",
        "stack": "",
        "error": "",
        "errorMessage": "",
        "contextValue": "AzureMLComputeInstanceRunningCanUse",
        "telemetryTrackingId": "1aaf6789-a95c-4258-9bef-fd0774917c27",
        "forceNewWindow": "false",
        "fileToOpenWhenConnectedExists": "false"
    },
    "expiresOn": 1713215300290
}
[Info - 2024-04-15 21:06:23.354] Telemetry tracker: {
    "sessionId": "",
    "telemetryTrackingId": "1aaf6789-a95c-4258-9bef-fd0774917c27"
}
[Debug - 2024-04-15 21:06:23.355] Telemetry Event: resolve/start Measures: undefined Props: {
    "abexp.assignmentcontext": "vsliv368cf:30146710;vspor879:30202332;vspor708:30202333;vspor363:30204092;binariesv615:30325510;vsaa593cf:30376535;c4g48928:30535728;a9j8j154:30646983;asynctok:30898717;bdiig495:31013172;",
    "sessionId": "",
    "telemetryTrackingId": "1aaf6789-a95c-4258-9bef-fd0774917c27",
    "resolveAttempt": "1",
    "tundra": "true"
}
[Trace - 2024-04-15 21:06:23.355] AuthenticationService.ensureLoginToSubscription called with arguments: [
    "810190d3-c779-4768-afec-3c158ec9853a",
    {
        "displayName": "ltcsonutka01",
        "targetType": "compute instance"
    }
]
[Trace - 2024-04-15 21:06:23.356] AuthenticationService.getSubscriptionById called with arguments: [
    "810190d3-c779-4768-afec-3c158ec9853a"
]
[Trace - 2024-04-15 21:06:23.356] AuthenticationService.listSubscriptions called with arguments: []
[Debug - 2024-04-15 21:06:24.155] Telemetry Event: authentication/needsLogin Measures: undefined Props: {
    "abexp.assignmentcontext": "vsliv368cf:30146710;vspor879:30202332;vspor708:30202333;vspor363:30204092;binariesv615:30325510;vsaa593cf:30376535;c4g48928:30535728;a9j8j154:30646983;asynctok:30898717;bdiig495:31013172;",
    "result": "false"
}
[Trace - 2024-04-15 21:06:24.404] Subscription.getWorkspace called with arguments: [
    "ihub-ltc-uat-ml",
    "ihub-ltc-ml-uat-rg"
]
[Error - 2024-04-15 21:06:24.894] Error: Extension 'ms-toolsai.vscode-ai-remote' CANNOT use API proposal: telemetry.
Its package.json#enabledApiProposals-property declares: resolvers but NOT telemetry.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api ms-toolsai.vscode-ai-remote
	at C (c:\Users\sonutka\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:140:51400)
	at get telemetryConfiguration [as telemetryConfiguration] (c:\Users\sonutka\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:162:23530)
	at l (c:\Users\sonutka\.vscode\extensions\ms-toolsai.vscode-ai-remote-0.48.0\dist\src\extension.js:2:721222)
	at l (c:\Users\sonutka\.vscode\extensions\ms-toolsai.vscode-ai-remote-0.48.0\dist\src\extension.js:2:721219)
	at l (c:\Users\sonutka\.vscode\extensions\ms-toolsai.vscode-ai-remote-0.48.0\dist\src\extension.js:2:721219)
	at l (c:\Users\sonutka\.vscode\extensions\ms-toolsai.vscode-ai-remote-0.48.0\dist\src\extension.js:2:721138)
	at l (c:\Users\sonutka\.vscode\extensions\ms-toolsai.vscode-ai-remote-0.48.0\dist\src\extension.js:2:721219)
	at l (c:\Users\sonutka\.vscode\extensions\ms-toolsai.vscode-ai-remote-0.48.0\dist\src\extension.js:2:721219)
	at l (c:\Users\sonutka\.vscode\extensions\ms-toolsai.vscode-ai-remote-0.48.0\dist\src\extension.js:2:721219)
	at l (c:\Users\sonutka\.vscode\extensions\ms-toolsai.vscode-ai-remote-0.48.0\dist\src\extension.js:2:721219)
	at l (c:\Users\sonutka\.vscode\extensions\ms-toolsai.vscode-ai-remote-0.48.0\dist\src\extension.js:2:721219)
	at l (c:\Users\sonutka\.vscode\extensions\ms-toolsai.vscode-ai-remote-0.48.0\dist\src\extension.js:2:721138)
	at s (c:\Users\sonutka\.vscode\extensions\ms-toolsai.vscode-ai-remote-0.48.0\dist\src\extension.js:2:720325)
	at c:\Users\sonutka\.vscode\extensions\ms-toolsai.vscode-ai-remote-0.48.0\dist\src\extension.js:2:1530819
	at Array.map (<anonymous>)
	at t.Logger.format (c:\Users\sonutka\.vscode\extensions\ms-toolsai.vscode-ai-remote-0.48.0\dist\src\extension.js:2:1530765)
	at t.Logger.trace (c:\Users\sonutka\.vscode\extensions\ms-toolsai.vscode-ai-remote-0.48.0\dist\src\extension.js:2:1530664)
	at o.value (c:\Users\sonutka\.vscode\extensions\ms-toolsai.vscode-ai-remote-0.48.0\dist\src\extension.js:2:1532052)
	at m.getRemoteTarget (c:\Users\sonutka\.vscode\extensions\ms-toolsai.vscode-ai-remote-0.48.0\dist\src\extension.js:2:1564039)
	at c:\Users\sonutka\.vscode\extensions\ms-toolsai.vscode-ai-remote-0.48.0\dist\src\extension.js:2:1621546
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5) []
[Trace - 2024-04-15 21:06:24.894] ComputeInstanceRemoteService.getRemoteTarget called with arguments: [object Object],[object Object],[object Object]
[Trace - 2024-04-15 21:06:26.284] AuthenticationService.getUserObjectId called with arguments: [
    "810190d3-c779-4768-afec-3c158ec9853a"
]
[Trace - 2024-04-15 21:06:26.284] AuthenticationService.getBearerToken called with arguments: [
    "810190d3-c779-4768-afec-3c158ec9853a"
]
[Trace - 2024-04-15 21:06:26.284] AuthenticationService.getAuthTokenResponse called with arguments: [
    "810190d3-c779-4768-afec-3c158ec9853a"
]
[Trace - 2024-04-15 21:06:26.284] AuthenticationService.getCredentials called with arguments: [
    "810190d3-c779-4768-afec-3c158ec9853a"
]
[Trace - 2024-04-15 21:06:26.284] AuthenticationService.promptLoginIfNecessaryAndBlock called with arguments: []
[Debug - 2024-04-15 21:06:26.288] Telemetry Event: authentication/needsLogin Measures: undefined Props: {
    "abexp.assignmentcontext": "vsliv368cf:30146710;vspor879:30202332;vspor708:30202333;vspor363:30204092;binariesv615:30325510;vsaa593cf:30376535;c4g48928:30535728;a9j8j154:30646983;asynctok:30898717;bdiig495:31013172;",
    "result": "false"
}
[Trace - 2024-04-15 21:06:26.288] AuthenticationService.getSubscriptionById called with arguments: [
    "810190d3-c779-4768-afec-3c158ec9853a"
]
[Trace - 2024-04-15 21:06:26.288] AuthenticationService.listSubscriptions called with arguments: []
[Debug - 2024-04-15 21:06:26.292] Telemetry Event: authentication/needsLogin Measures: undefined Props: {
    "abexp.assignmentcontext": "vsliv368cf:30146710;vspor879:30202332;vspor708:30202333;vspor363:30204092;binariesv615:30325510;vsaa593cf:30376535;c4g48928:30535728;a9j8j154:30646983;asynctok:30898717;bdiig495:31013172;",
    "result": "false"
}
[Info - 2024-04-15 21:06:26.503] [Azure ML JS SDK]Workspace ihub-ltc-uat-ml has a private endpoint connection
[Debug - 2024-04-15 21:06:26.503] Telemetry Event: azureml-js-sdk/isPrivateLink Measures: undefined Props: {
    "abexp.assignmentcontext": "vsliv368cf:30146710;vspor879:30202332;vspor708:30202333;vspor363:30204092;binariesv615:30325510;vsaa593cf:30376535;c4g48928:30535728;a9j8j154:30646983;asynctok:30898717;bdiig495:31013172;",
    "isPrivateLink": "true"
}
[Debug - 2024-04-15 21:06:26.503] Workspace is behind a private link and public network access is disabled
[Debug - 2024-04-15 21:06:26.503] Ensuring that compute instance ltcsonutka01 is running
[Debug - 2024-04-15 21:06:26.503] Compute instance ltcsonutka01 is already running
[Trace - 2024-04-15 21:06:26.504] AuthenticationService.getBearerToken called with arguments: [
    "810190d3-c779-4768-afec-3c158ec9853a"
]
[Trace - 2024-04-15 21:06:26.504] AuthenticationService.getAuthTokenResponse called with arguments: [
    "810190d3-c779-4768-afec-3c158ec9853a"
]
[Trace - 2024-04-15 21:06:26.504] AuthenticationService.getCredentials called with arguments: [
    "810190d3-c779-4768-afec-3c158ec9853a"
]
[Trace - 2024-04-15 21:06:26.504] AuthenticationService.promptLoginIfNecessaryAndBlock called with arguments: []
[Debug - 2024-04-15 21:06:26.514] Telemetry Event: authentication/needsLogin Measures: undefined Props: {
    "abexp.assignmentcontext": "vsliv368cf:30146710;vspor879:30202332;vspor708:30202333;vspor363:30204092;binariesv615:30325510;vsaa593cf:30376535;c4g48928:30535728;a9j8j154:30646983;asynctok:30898717;bdiig495:31013172;",
    "result": "false"
}
[Trace - 2024-04-15 21:06:26.514] AuthenticationService.getSubscriptionById called with arguments: [
    "810190d3-c779-4768-afec-3c158ec9853a"
]
[Trace - 2024-04-15 21:06:26.514] AuthenticationService.listSubscriptions called with arguments: []
[Debug - 2024-04-15 21:06:26.520] Telemetry Event: authentication/needsLogin Measures: undefined Props: {
    "abexp.assignmentcontext": "vsliv368cf:30146710;vspor879:30202332;vspor708:30202333;vspor363:30204092;binariesv615:30325510;vsaa593cf:30376535;c4g48928:30535728;a9j8j154:30646983;asynctok:30898717;bdiig495:31013172;",
    "result": "false"
}
[Info - 2024-04-15 21:06:26.752] Compute instance to connect to: https://ltcsonutka01.eastus2.instances.azureml.ms/
[Info - 2024-04-15 21:06:26.752] Remote target: {
    "displayName": "ltcsonutka01",
    "estimatedVMPrice": "0.77",
    "targetType": "compute instance",
    "terminalUrl": {
        "url": "https://ltcsonutka01.eastus2.instances.azureml.ms/",
        "type": "Jupyter"
    },
    "vmSize": "Standard_D16s_v3"
}
[Debug - 2024-04-15 21:06:26.753] Telemetry Event: resolve/targetInfo Measures: undefined Props: {
    "abexp.assignmentcontext": "vsliv368cf:30146710;vspor879:30202332;vspor708:30202333;vspor363:30204092;binariesv615:30325510;vsaa593cf:30376535;c4g48928:30535728;a9j8j154:30646983;asynctok:30898717;bdiig495:31013172;",
    "isActivationEvent": "false",
    "lastStep": "",
    "result": "Succeeded",
    "stack": "",
    "error": "",
    "errorMessage": "",
    "telemetryTrackingId": "1aaf6789-a95c-4258-9bef-fd0774917c27",
    "resolveAttempt": "1",
    "isReconnection": "false",
    "tundra": "true",
    "contextValue": "AzureMLComputeInstanceRunningCanUse",
    "forceNewWindow": "false",
    "fileToOpenWhenConnectedExists": "false",
    "sessionId": "",
    "vmSize": "Standard_D16s_v3",
    "estimatedVMPrice": "0.77",
    "computeState": "Running",
    "subscription": "810190d3-c779-4768-afec-3c158ec9853a",
    "isPrivateLink": "true",
    "targetType": "compute instance",
    "isEnvironmentContainer": "false"
}
[Trace - 2024-04-15 21:06:26.753] Resolver.handleAzureMLExtensionActivation called with arguments: [
    "compute instance"
]
[Trace - 2024-04-15 21:06:26.753] Resolver.handlePassedFileContext called with arguments: [
    "amlext+2f737562736372697074696f6e732f38313031393064332d633737392d343736382d616665632d3363313538656339383533612f7265736f7572636547726f7570732f696875622d6c74632d6d6c2d7561742d72672f70726f7669646572732f4d6963726f736f66742e4d616368696e654c6561726e696e6753657276696365732f776f726b7370616365732f696875622d6c74632d7561742d6d6c2f636f6d70757465732f6c7463736f6e75746b613031",
    null
]
[Trace - 2024-04-15 21:06:26.754] AuthenticationService.getBearerToken called with arguments: [
    "810190d3-c779-4768-afec-3c158ec9853a"
]
[Trace - 2024-04-15 21:06:26.754] AuthenticationService.getAuthTokenResponse called with arguments: [
    "810190d3-c779-4768-afec-3c158ec9853a"
]
[Trace - 2024-04-15 21:06:26.754] AuthenticationService.getCredentials called with arguments: [
    "810190d3-c779-4768-afec-3c158ec9853a"
]
[Trace - 2024-04-15 21:06:26.754] AuthenticationService.promptLoginIfNecessaryAndBlock called with arguments: []
[Debug - 2024-04-15 21:06:26.759] Telemetry Event: authentication/needsLogin Measures: undefined Props: {
    "abexp.assignmentcontext": "vsliv368cf:30146710;vspor879:30202332;vspor708:30202333;vspor363:30204092;binariesv615:30325510;vsaa593cf:30376535;c4g48928:30535728;a9j8j154:30646983;asynctok:30898717;bdiig495:31013172;",
    "result": "false"
}
[Trace - 2024-04-15 21:06:26.759] AuthenticationService.getSubscriptionById called with arguments: [
    "810190d3-c779-4768-afec-3c158ec9853a"
]
[Trace - 2024-04-15 21:06:26.759] AuthenticationService.listSubscriptions called with arguments: []
[Debug - 2024-04-15 21:06:26.761] Telemetry Event: authentication/needsLogin Measures: undefined Props: {
    "abexp.assignmentcontext": "vsliv368cf:30146710;vspor879:30202332;vspor708:30202333;vspor363:30204092;binariesv615:30325510;vsaa593cf:30376535;c4g48928:30535728;a9j8j154:30646983;asynctok:30898717;bdiig495:31013172;",
    "result": "false"
}
[Trace - 2024-04-15 21:06:26.982] TerminalFactory.createTerminal called with arguments: [
    {
        "baseUrl": "https://ltcsonutka01.eastus2.instances.azureml.ms/",
        "authorizationHeader": "REDACTED",
        "displayName": "ltcsonutka01",
        "token": "REDACTED",
        "type": "Jupyter"
    },
    "Large"
]
[Debug - 2024-04-15 21:06:26.983] New Jupyter terminal created with id: 1
[Error - 2024-04-15 21:06:26.983] Error: Extension 'ms-toolsai.vscode-ai-remote' CANNOT use API proposal: telemetry.
Its package.json#enabledApiProposals-property declares: resolvers but NOT telemetry.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api ms-toolsai.vscode-ai-remote
	at C (c:\Users\sonutka\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:140:51400)
	at get telemetryConfiguration [as telemetryConfiguration] (c:\Users\sonutka\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:162:23530)
	at l (c:\Users\sonutka\.vscode\extensions\ms-toolsai.vscode-ai-remote-0.48.0\dist\src\extension.js:2:721222)
	at l (c:\Users\sonutka\.vscode\extensions\ms-toolsai.vscode-ai-remote-0.48.0\dist\src\extension.js:2:721219)
	at l (c:\Users\sonutka\.vscode\extensions\ms-toolsai.vscode-ai-remote-0.48.0\dist\src\extension.js:2:721219)
	at l (c:\Users\sonutka\.vscode\extensions\ms-toolsai.vscode-ai-remote-0.48.0\dist\src\extension.js:2:721138)
	at l (c:\Users\sonutka\.vscode\extensions\ms-toolsai.vscode-ai-remote-0.48.0\dist\src\extension.js:2:721219)
	at l (c:\Users\sonutka\.vscode\extensions\ms-toolsai.vscode-ai-remote-0.48.0\dist\src\extension.js:2:721219)
	at l (c:\Users\sonutka\.vscode\extensions\ms-toolsai.vscode-ai-remote-0.48.0\dist\src\extension.js:2:721219)
	at l (c:\Users\sonutka\.vscode\extensions\ms-toolsai.vscode-ai-remote-0.48.0\dist\src\extension.js:2:721219)
	at l (c:\Users\sonutka\.vscode\extensions\ms-toolsai.vscode-ai-remote-0.48.0\dist\src\extension.js:2:721138)
	at s (c:\Users\sonutka\.vscode\extensions\ms-toolsai.vscode-ai-remote-0.48.0\dist\src\extension.js:2:720325)
	at c:\Users\sonutka\.vscode\extensions\ms-toolsai.vscode-ai-remote-0.48.0\dist\src\extension.js:2:1530819
	at Array.map (<anonymous>)
	at t.Logger.format (c:\Users\sonutka\.vscode\extensions\ms-toolsai.vscode-ai-remote-0.48.0\dist\src\extension.js:2:1530765)
	at t.Logger.trace (c:\Users\sonutka\.vscode\extensions\ms-toolsai.vscode-ai-remote-0.48.0\dist\src\extension.js:2:1530664)
	at o.value (c:\Users\sonutka\.vscode\extensions\ms-toolsai.vscode-ai-remote-0.48.0\dist\src\extension.js:2:1532052)
	at c:\Users\sonutka\.vscode\extensions\ms-toolsai.vscode-ai-remote-0.48.0\dist\src\extension.js:2:1622682
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5) []
[Trace - 2024-04-15 21:06:26.983] Resolver.setupRemoteDependencies called with arguments: [object Object],[object Object],compute instance
[Error - 2024-04-15 21:06:26.984] Error: Extension 'ms-toolsai.vscode-ai-remote' CANNOT use API proposal: telemetry.
Its package.json#enabledApiProposals-property declares: resolvers but NOT telemetry.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api ms-toolsai.vscode-ai-remote
	at C (c:\Users\sonutka\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:140:51400)
	at get telemetryConfiguration [as telemetryConfiguration] (c:\Users\sonutka\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:162:23530)
	at l (c:\Users\sonutka\.vscode\extensions\ms-toolsai.vscode-ai-remote-0.48.0\dist\src\extension.js:2:721222)
	at l (c:\Users\sonutka\.vscode\extensions\ms-toolsai.vscode-ai-remote-0.48.0\dist\src\extension.js:2:721219)
	at l (c:\Users\sonutka\.vscode\extensions\ms-toolsai.vscode-ai-remote-0.48.0\dist\src\extension.js:2:721219)
	at l (c:\Users\sonutka\.vscode\extensions\ms-toolsai.vscode-ai-remote-0.48.0\dist\src\extension.js:2:721138)
	at l (c:\Users\sonutka\.vscode\extensions\ms-toolsai.vscode-ai-remote-0.48.0\dist\src\extension.js:2:721219)
	at l (c:\Users\sonutka\.vscode\extensions\ms-toolsai.vscode-ai-remote-0.48.0\dist\src\extension.js:2:721219)
	at l (c:\Users\sonutka\.vscode\extensions\ms-toolsai.vscode-ai-remote-0.48.0\dist\src\extension.js:2:721219)
	at l (c:\Users\sonutka\.vscode\extensions\ms-toolsai.vscode-ai-remote-0.48.0\dist\src\extension.js:2:721219)
	at l (c:\Users\sonutka\.vscode\extensions\ms-toolsai.vscode-ai-remote-0.48.0\dist\src\extension.js:2:721138)
	at s (c:\Users\sonutka\.vscode\extensions\ms-toolsai.vscode-ai-remote-0.48.0\dist\src\extension.js:2:720325)
	at c:\Users\sonutka\.vscode\extensions\ms-toolsai.vscode-ai-remote-0.48.0\dist\src\extension.js:2:1530819
	at Array.map (<anonymous>)
	at t.Logger.format (c:\Users\sonutka\.vscode\extensions\ms-toolsai.vscode-ai-remote-0.48.0\dist\src\extension.js:2:1530765)
	at t.Logger.trace (c:\Users\sonutka\.vscode\extensions\ms-toolsai.vscode-ai-remote-0.48.0\dist\src\extension.js:2:1530664)
	at o.value (c:\Users\sonutka\.vscode\extensions\ms-toolsai.vscode-ai-remote-0.48.0\dist\src\extension.js:2:1532052)
	at N.setupRemoteDependencies (c:\Users\sonutka\.vscode\extensions\ms-toolsai.vscode-ai-remote-0.48.0\dist\src\extension.js:2:1627693)
	at o.value (c:\Users\sonutka\.vscode\extensions\ms-toolsai.vscode-ai-remote-0.48.0\dist\src\extension.js:2:1532093)
	at c:\Users\sonutka\.vscode\extensions\ms-toolsai.vscode-ai-remote-0.48.0\dist\src\extension.js:2:1622682
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5) []
[Trace - 2024-04-15 21:06:26.984] TundraValidator.isTundraAvailable called with arguments: [object Object]
[Info - 2024-04-15 21:06:26.984] Checking if Tundra is available on remote
[Debug - 2024-04-15 21:06:26.984] [TerminalId: 1]Running script with args: {
    "preserveCommandInBashHistory": false,
    "minify": true
}
[Debug - 2024-04-15 21:06:28.898] [TerminalId: 1]Retrying script. Remaining retries: 3. Error:  {
    "code": 72,
    "additionalProps": {
        "name": "Error"
    },
    "name": "TerminalError"
}
[Debug - 2024-04-15 21:06:31.707] [TerminalId: 1]Retrying script. Remaining retries: 2. Error:  {
    "code": 72,
    "additionalProps": {
        "name": "Error"
    },
    "name": "TerminalError"
}
[Debug - 2024-04-15 21:06:35.534] [TerminalId: 1]Retrying script. Remaining retries: 1. Error:  {
    "code": 72,
    "additionalProps": {
        "name": "Error"
    },
    "name": "TerminalError"
}
[Debug - 2024-04-15 21:06:41.356] Telemetry Event: resolve/error Measures: undefined Props: {
    "abexp.assignmentcontext": "vsliv368cf:30146710;vspor879:30202332;vspor708:30202333;vspor363:30204092;binariesv615:30325510;vsaa593cf:30376535;c4g48928:30535728;a9j8j154:30646983;asynctok:30898717;bdiig495:31013172;",
    "sessionId": "",
    "telemetryTrackingId": "1aaf6789-a95c-4258-9bef-fd0774917c27",
    "stack": "TerminalError: Invalid response: 403 Forbidden\n\tat s (c:\\Users\\sonutka\\.vscode\\extensions\\ms-toolsai.vscode-ai-remote-0.48.0\\dist\\src\\extension.js:2:1556074)\n\tat process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n\tat async d.isTundraAvailable (c:\\Users\\sonutka\\.vscode\\extensions\\ms-toolsai.vscode-ai-remote-0.48.0\\dist\\src\\extension.js:2:1641604)\n\tat async N.setupRemoteDependencies (c:\\Users\\sonutka\\.vscode\\extensions\\ms-toolsai.vscode-ai-remote-0.48.0\\dist\\src\\extension.js:2:1627666)\n\tat async c:\\Users\\sonutka\\.vscode\\extensions\\ms-toolsai.vscode-ai-remote-0.48.0\\dist\\src\\extension.js:2:1622671",
    "message": "Invalid response: 403 Forbidden",
    "code": "72",
    "additionalProps": "object",
    "name": "TerminalError"
}
[Trace - 2024-04-15 21:06:41.356] ResolverErrorHandler.handleError called with arguments: [
    {
        "telemetry": {
            "properties": {
                "isActivationEvent": "false",
                "lastStep": "",
                "result": "Succeeded",
                "stack": "",
                "error": "",
                "errorMessage": "",
                "telemetryTrackingId": "1aaf6789-a95c-4258-9bef-fd0774917c27",
                "resolveAttempt": "1",
                "isReconnection": "false",
                "tundra": "true",
                "contextValue": "AzureMLComputeInstanceRunningCanUse",
                "forceNewWindow": "false",
                "fileToOpenWhenConnectedExists": "false",
                "sessionId": "",
                "vmSize": "Standard_D16s_v3",
                "estimatedVMPrice": "0.77",
                "computeState": "Running",
                "subscription": "810190d3-c779-4768-afec-3c158ec9853a",
                "isPrivateLink": "true",
                "targetType": "compute instance",
                "isEnvironmentContainer": "false"
            },
            "measurements": {
                "duration": 0
            },
            "suppressIfSuccessful": false,
            "suppressAll": false
        },
        "errorHandling": {
            "suppressDisplay": false,
            "rethrow": true,
            "issueProperties": {}
        },
        "ui": {
            "_onDidFinishPromptEmitter": {
                "w": 0
            },
            "_isPrompting": false,
            "_context": "[Circular]"
        },
        "valuesToMask": [],
        "callbackId": "Resolver.resolve"
    },
    {
        "code": 72,
        "additionalProps": {
            "name": "Error"
        },
        "name": "TerminalError"
    }
]
[Error - 2024-04-15 21:06:41.372] Error: Connection is forbidden. Please make sure that you are logged in with the right Azure Account and the Remote target exists. (Error: Invalid response: 403 Forbidden)
[Error - 2024-04-15 21:06:41.564] Error: command 'azureml.internal.activate' not found
    at S.n (vscode-file://vscode-app/c:/Users/sonutka/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1602:23049)
    at S.executeCommand (vscode-file://vscode-app/c:/Users/sonutka/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1602:22978) []
[Error - 2024-04-15 21:06:52.873] Error: Operation cancelled.
	at c:\Users\sonutka\.vscode\extensions\ms-toolsai.vscode-ai-remote-0.48.0\dist\src\extension.js:2:1493942 []
