### ISSUE TITLE
Issue with installing Vscode extensions on Vscode server

### ISSUE THREAD

**Issue by dj674** [microsoft/vscode-tools-for-ai#2467]
So after installing the Azure machine learning, Azure machine learning remote & Jupyter extensions in Vscode locally, we are able to then install the Vscode server software remotely on an Azure Machine learning instance and connect successfully.

However, when i try to install the Jupyter extension on the Azure Machine Learning instance from my local vscode, it doesn't install anything and 
doesn't give any errors in the remoteagent.log on the ML instance. 

What could the issue be? Am I looking in the right place for errors?

Can you provide any guidance.

Thankyou.

**Comment by JerryYangKai** [comment]
Hello @dj674 
Jupyter extension is not owned by us, if you have some questions about it, please create an issue here.
https://github.com/Microsoft/vscode-jupyter/issues

**Comment by dj674** [comment]
Hi,

It's not exclusive to jupyter extension, it can be python ones too.

What logs can I be looking at on the Azure ML instance to try and see where the issue is to provide to additional information? if it is available.

Is the remoteagent.log, the only relevant log?

**Comment by JerryYangKai** [comment]
@dj674  If there's some question about Azure Machine learning compute instance, I think the right place for support is here https://azure.microsoft.com/en-us/support/

**Comment by Siglud** [comment]
@dj674  So, the problem is you connected to an Azure ML compute and tried to install the Jupyter extension locally and encounter an error?

Could you please paste your `Extension Host` log in your OUTPUT table?

![Image](https://github.com/user-attachments/assets/0296bcd8-38cc-41c9-adbc-6943a10dffa0)

**Comment by dj674** [comment]
Hi,

Just to confirm, the issue is installing extensions on the ML instance from my Local machine...

![Image](https://github.com/user-attachments/assets/3e5dd600-3fc0-4c4d-9008-02ea55ec8924)

![Image](https://github.com/user-attachments/assets/a77d4f26-e422-43b2-9e05-ae29301ac206)

Nothing happens, no extensions are installed on my ML instance.

As requested, this is the "Extension Host" log...

2024-11-25 10:11:35.314 [info] Extension host with pid 10980 started
2024-11-25 10:11:35.530 [info] ExtensionService#_doActivateExtension vscode.git-base, startup: true, activationEvent: '*', root cause: vscode.git
2024-11-25 10:11:35.868 [info] ExtensionService#_doActivateExtension vscode.git, startup: true, activationEvent: '*'
2024-11-25 10:11:36.012 [info] ExtensionService#_doActivateExtension vscode.github, startup: true, activationEvent: '*'
2024-11-25 10:11:36.457 [info] Eager extensions activated
2024-11-25 10:11:36.572 [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch, startup: false, activationEvent: 'onStartupFinished'
2024-11-25 10:11:36.579 [info] ExtensionService#_doActivateExtension vscode.merge-conflict, startup: false, activationEvent: 'onStartupFinished'
2024-11-25 10:11:58.841 [info] ExtensionService#_doActivateExtension vscode.emmet, startup: false, activationEvent: 'onLanguage'
2024-11-25 10:12:33.491 [info] ExtensionService#_doActivateExtension ms-toolsai.jupyter, startup: false, activationEvent: 'onWalkthrough:jupyterWelcome'
2024-11-25 10:12:44.205 [info] ExtensionService#_doActivateExtension ms-toolsai.vscode-ai-remote, startup: false, activationEvent: 'api', root cause: ms-toolsai.jupyter
2024-11-25 10:12:44.661 [info] ExtensionService#_doActivateExtension ms-toolsai.vscode-ai, startup: false, activationEvent: 'api', root cause: ms-toolsai.jupyter
2024-11-25 10:12:50.480 [info] ExtensionService#_doActivateExtension vscode.microsoft-authentication, startup: false, activationEvent: 'onAuthenticationRequest:microsoft'
2024-11-25 10:22:24.179 [info] Extension host terminating: renderer closed the MessagePort
2024-11-25 10:22:24.226 [error] Canceled: Canceled
	at new eA (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:109321)
	at Zb.U (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:113933)
	at s.<computed>.n.charCodeAt.s.<computed> (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:111427)
	at T0.g (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:32325)
	at T0.executeCommand (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:31826)
	at r.registerCommand.description (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:31156)
	at T0.h (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:32845)
	at T0.g (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:31919)
	at T0.executeCommand (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:31826)
	at Object.executeCommand (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:156:37049)
	at zt.set (c:\Users\xxxxxxxxxxxxxx\.vscode\extensions\ms-toolsai.jupyter-2024.9.1\dist\extension.node.js:304:165067)
	at Tb.dispose (c:\Users\xxxxxxxxxxxx\.vscode\extensions\ms-toolsai.jupyter-2024.9.1\dist\extension.node.js:342:8136)
	at Si (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:24:701)
	at file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:118:14995
	at file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:24:1011
	at Object.dispose (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:7:2146)
	at hB.eb (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:118:11922)
	at file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:118:9877
	at Array.map (<anonymous>)
	at hB.$ (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:118:9865)
	at hB.terminate (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:118:10108)
	at M3.terminate (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:119:1424)
	at ps (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:174:15058)
	at MessagePortMain.<anonymous> (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:174:11603)
	at MessagePortMain.emit (node:events:519:28)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:2619) setContext undefined
2024-11-25 10:22:24.273 [info] Extension host with pid 10980 exiting with code 0
2024-11-25 10:22:25.899 [info] Extension host with pid 6488 started
2024-11-25 10:22:25.899 [info] Skipping acquiring lock for c:\Users\xxxxxxxxxxxxxxx\AppData\Roaming\Code\User\workspaceStorage\33b40fe0513bab217fa67fae7538245a.
2024-11-25 10:22:25.899 [info] $getCanonicalURI invoked for authority (amlext)
2024-11-25 10:22:25.912 [info] ExtensionService#_doActivateExtension ms-toolsai.vscode-ai-remote, startup: false, activationEvent: 'onResolveRemoteAuthority:amlext'
2024-11-25 10:22:26.560 [info] [resolveAuthority(amlext,1)][0ms] activating remote resolvers amlext+2f737562736372697074696f6e732f62303735653639372d366464622d343266342d383133312d3530663734663362313236642f7265736f7572636547726f7570732f6963682d72672d6d6c2d74646573757070686f7573652d756b732d746573742f70726f7669646572732f4d6963726f736f66742e4d616368696e654c6561726e696e6753657276696365732f776f726b7370616365732f6963682d6d6c772d6d6c2d74646573757070686f7573652d756b732d746573742f636f6d70757465732f647061706164696d697472696f752d2d6469783568343162
2024-11-25 10:22:26.560 [info] [resolveAuthority(amlext,1)][0ms] activating resolver for amlext+2f737562736372697074696f6e732f62303735653639372d366464622d343266342d383133312d3530663734663362313236642f7265736f7572636547726f7570732f6963682d72672d6d6c2d74646573757070686f7573652d756b732d746573742f70726f7669646572732f4d6963726f736f66742e4d616368696e654c6561726e696e6753657276696365732f776f726b7370616365732f6963682d6d6c772d6d6c2d74646573757070686f7573652d756b732d746573742f636f6d70757465732f647061706164696d697472696f752d2d6469783568343162...
2024-11-25 10:22:26.561 [info] [resolveAuthority(amlext,1)][0ms] invoking final resolve()...
2024-11-25 10:22:26.576 [info] ExtensionService#_doActivateExtension vscode.microsoft-authentication, startup: false, activationEvent: 'onAuthenticationRequest:microsoft'
2024-11-25 10:22:27.568 [info] [resolveAuthority(amlext,1)][1007ms] waiting...
2024-11-25 10:22:28.583 [info] [resolveAuthority(amlext,1)][2022ms] waiting...
2024-11-25 10:22:29.597 [info] [resolveAuthority(amlext,1)][3036ms] waiting...
2024-11-25 10:22:30.603 [info] [resolveAuthority(amlext,1)][4042ms] waiting...
2024-11-25 10:22:31.616 [info] [resolveAuthority(amlext,1)][5055ms] waiting...
2024-11-25 10:22:32.628 [info] [resolveAuthority(amlext,1)][6068ms] waiting...
2024-11-25 10:22:33.634 [info] [resolveAuthority(amlext,1)][7073ms] waiting...
2024-11-25 10:22:34.646 [info] [resolveAuthority(amlext,1)][8086ms] waiting...
2024-11-25 10:22:35.659 [info] [resolveAuthority(amlext,1)][9099ms] waiting...
2024-11-25 10:22:36.663 [info] [resolveAuthority(amlext,1)][10102ms] waiting...
2024-11-25 10:22:37.675 [info] [resolveAuthority(amlext,1)][11114ms] waiting...
2024-11-25 10:22:38.678 [info] [resolveAuthority(amlext,1)][12117ms] waiting...
2024-11-25 10:22:39.685 [info] [resolveAuthority(amlext,1)][13124ms] waiting...
2024-11-25 10:22:40.695 [info] [resolveAuthority(amlext,1)][14134ms] waiting...
2024-11-25 10:22:41.702 [info] [resolveAuthority(amlext,1)][15141ms] waiting...
2024-11-25 10:22:42.708 [info] [resolveAuthority(amlext,1)][16148ms] waiting...
2024-11-25 10:22:43.709 [info] [resolveAuthority(amlext,1)][17148ms] waiting...
2024-11-25 10:22:44.346 [info] [resolveAuthority(amlext,1)][17785ms] setting tunnel factory...
2024-11-25 10:22:44.346 [info] [resolveAuthority(amlext,1)][17785ms] returned 127.0.0.1:52401
2024-11-25 10:22:46.656 [info] Eager extensions activated

**Comment by dj674** [comment]
Hi,

We upgraded to Vscode 1.96 but are still unable to install extensions.

The only logs that gave any additional information was Vscode "Window" logs:-

<img width="648" alt="Image" src="https://github.com/user-attachments/assets/0915aa9d-6466-49f3-80f1-854fc8bcbc9e" />

Are there any other logs that you think would be useful?

**Comment by JerryYangKai** [comment]
@Siglud  Please help to look at it, thanks!

**Comment by Siglud** [comment]
> Hi,
> 
> We upgraded to Vscode 1.96 but are still unable to install extensions.
> 
> The only logs that gave any additional information was Vscode "Window" logs:-
> 
> <img alt="Image" width="648" src="https://private-user-images.githubusercontent.com/104076521/401553368-0915aa9d-6466-49f3-80f1-854fc8bcbc9e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY5MTEwMzAsIm5iZiI6MTczNjkxMDczMCwicGF0aCI6Ii8xMDQwNzY1MjEvNDAxNTUzMzY4LTA5MTVhYTlkLTY0NjYtNDlmMy04MGYxLTg1NGZjOGJjYmM5ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDExNVQwMzEyMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04Yjc1MzEwZTE3YWFmMjJhNjY3YzUyOTVmZTY5MmJjNTU2NjEzYjU5ODZhMTY2ZTJkNWQ0MDNkNzI2YmEwMzczJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.mFMW5R7rhRpUFkniVQYlQcg23hYTw9jzzWOC0kC80-A">
> Are there any other logs that you think would be useful?

Please check those point:

* Is your workspace under VNET and disabled outbound traffic to `marketplace.visualstudio.com`? Please follow [this instruction](https://learn.microsoft.com/en-us/azure/machine-learning/how-to-access-azureml-behind-firewall?view=azureml-api-2&tabs=ipaddress%2Cpublic#scenario-visual-studio-code) to set you network outbound rules if you are in a private network
* Please try to use `Azure ML - Remote: Uninstall VS Code Server on Computer instance` to make sure you get the last version of VS Code Server in your computer.

![Image](https://github.com/user-attachments/assets/cb7ac74a-7802-4cef-85ad-4146f496bda0)
