### ISSUE TITLE
List jobs failed, Unexpected end of JSON input

### ISSUE THREAD

**Issue by Davidham3** [Microsoft/vscode-tools-for-ai#34]
Hi, I use VS code to submit a test script to one of my remote linux machine. After submitting the job, I click the button "List Jobs", it shows that "Error - Can not parse list job result".

The terminal shows:
Parse job list faild:

Error: Unexpected end of JSON input

But when I change to submit jobs to another linux machine, there is no error shows up.
How can I debug that?

**Comment by qfyin** [comment]
Hi @Davidham3 , thanks for reporting the issue.
Could you please check the log file under %appdata%\Microsoft\ToolsForAI\.vscode ?
( $HOME/Library/Caches/AIToolsForVSCode on mac)
You can identify the relevant log file by the timestamp in file name.
It might be helpful if you could attach the log here.

**Comment by qfyin** [comment]
Hi @Davidham3 , thanks for reporting the issue.
Could you please check the log file under %appdata%\Microsoft\ToolsForAI\.vscode ?
( $HOME/Library/Caches/AIToolsForVSCode on mac)
You can identify the relevant log file by the timestamp in file name.
It might be helpful if you could attach the log here.

**Comment by Davidham3** [comment]
@qfyin I got this:
{"level":"info","message":"VSCode Tools For AI 0.1.8","timestamp":"2018-05-24T13:42:25.492Z"}
{"level":"info","message":"Platform: darwin","timestamp":"2018-05-24T13:42:25.493Z"}
{"meta":"","stack":"SyntaxError: Unexpected end of JSON input\n\tat JSON.parse (<anonymous>)\n\tat LinuxVMJobService.getJobList (/Users/davidham3/.vscode/extensions/ms-toolsai.vscode-ai-0.1.8/out/src/configurations/linuxVM/linuxVMJobService.js:150:24)\n\tat <anonymous>\n\tat process._tickCallback (internal/process/next_tick.js:109:7)","level":"error","message":"Unexpected end of JSON input","timestamp":"2018-05-24T13:42:51.064Z"}
{"meta":"/data/job/list?cache=1&refresh=false","stack":"Error: Can not parse list job result\n\tat LinuxVMJobService.getJobList (/Users/davidham3/.vscode/extensions/ms-toolsai.vscode-ai-0.1.8/out/src/configurations/linuxVM/linuxVMJobService.js:155:19)\n\tat <anonymous>\n\tat process._tickCallback (internal/process/next_tick.js:109:7)","level":"error","message":"Can not parse list job result","timestamp":"2018-05-24T13:42:51.066Z"}
Do you know what's the problem of the joblist?

**Comment by linmajia** [comment]
@Davidham3 , thank you very much for the feedback.

There may be old job information which is incompatible with the new releases. I suggest that you clear all job histories by renaming the job directory, and then retry submission and listing:

```bash
mv /tmp/aitools /tmp/aitools.old
```

**Comment by linmajia** [comment]
@Davidham3 , does this issue still exist?

Thank you.

**Comment by Davidham3** [comment]
@linmajia , well, I tried to change a remote machine to submit my code, it still doesn't work. Error like this:
```
{"level":"info","message":"VSCode Tools For AI 0.1.9","timestamp":"2018-07-13T02:18:46.513Z"}
{"level":"info","message":"Platform: win32","timestamp":"2018-07-13T02:18:46.514Z"}
{"meta":"","stack":"SyntaxError: Unexpected end of JSON input
	at JSON.parse (<anonymous>)
	at LinuxVMJobService.getJobList (C:\Users\Davidham3\.vscode\extensions\ms-toolsai.vscode-ai-0.1.9\out\src\configurations\linuxVM\linuxVMJobService.js:150:24)
	at <anonymous>
	at process._tickCallback (internal/process/next_tick.js:109:7)","level":"error","message":"Unexpected end of JSON input","timestamp":"2018-07-13T02:19:34.041Z"}
{"meta":"/data/job/list?cache=1&refresh=false","stack":"Error: Can not parse list job result
	at LinuxVMJobService.getJobList (C:\Users\Davidham3\.vscode\extensions\ms-toolsai.vscode-ai-0.1.9\out\src\configurations\linuxVM\linuxVMJobService.js:155:19)
	at <anonymous>
	at process._tickCallback (internal/process/next_tick.js:109:7)","level":"error","message":"Can not parse list job result","timestamp":"2018-07-13T02:19:34.042Z"}
{"meta":"","stack":"SyntaxError: Unexpected end of JSON input
	at JSON.parse (<anonymous>)
	at LinuxVMJobService.getJobList (C:\Users\Davidham3\.vscode\extensions\ms-toolsai.vscode-ai-0.1.9\out\src\configurations\linuxVM\linuxVMJobService.js:150:24)
	at <anonymous>
	at process._tickCallback (internal/process/next_tick.js:109:7)","level":"error","message":"Unexpected end of JSON input","timestamp":"2018-07-13T02:19:41.653Z"}
{"meta":"/data/job/list?cache=1&refresh=false","stack":"Error: Can not parse list job result
	at LinuxVMJobService.getJobList (C:\Users\Davidham3\.vscode\extensions\ms-toolsai.vscode-ai-0.1.9\out\src\configurations\linuxVM\linuxVMJobService.js:155:19)
	at <anonymous>
	at process._tickCallback (internal/process/next_tick.js:109:7)","level":"error","message":"Can not parse list job result","timestamp":"2018-07-13T02:19:41.654Z"}
{"stack":"Error: Batch AI: Please login first
	at Object.getBatchAIClient (C:\Users\Davidham3\.vscode\extensions\ms-toolsai.vscode-ai-0.1.9\out\src\configurations\batchAI\batchAIUtil.js:42:15)
	at BatchAIClusterProvider.getClusters (C:\Users\Davidham3\.vscode\extensions\ms-toolsai.vscode-ai-0.1.9\out\src\configurations\batchAI\batchAIClusterProvider.js:185:34)
	at BatchAIClusterProvider.list (C:\Users\Davidham3\.vscode\extensions\ms-toolsai.vscode-ai-0.1.9\out\src\configurations\batchAI\batchAIClusterProvider.js:96:37)
	at BatchAIPlatformTreeNode.getChildren (C:\Users\Davidham3\.vscode\extensions\ms-toolsai.vscode-ai-0.1.9\out\src\treeView\configExplorer\configExplorerTreeNode.js:76:49)
	at ConfigExplorerTreeDataProvider.getChildren (C:\Users\Davidham3\.vscode\extensions\ms-toolsai.vscode-ai-0.1.9\out\src\treeView\configExplorer\configExplorerTreeDataProvider.js:51:25)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:493:167
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:109:515
	at new n.Class.derive._oncancel (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:84:560)
	at Object.t.asWinJsPromise (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:109:478)
	at t.fetchChildrenNodes (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:493:119)
	at t.getChildren (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:490:586)
	at e.$getChildren (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:488:210)
	at e._doInvokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:658:87)
	at e._invokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:657:779)
	at e._receiveRequest (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:656:851)
	at e._receiveOneMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:656:620)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:655:544
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:658:673
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:96:599
	at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:97:917)
	at u (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:159:721)
	at Socket.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:159:898)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Socket.Readable.push (_stream_readable.js:136:10)
	at Pipe.onread (net.js:560:20)","level":"error","message":"Batch AI: Please login first","timestamp":"2018-07-13T02:20:39.120Z"}
{"meta":"","stack":"SyntaxError: Unexpected end of JSON input
	at JSON.parse (<anonymous>)
	at LinuxVMJobService.getJobList (C:\Users\Davidham3\.vscode\extensions\ms-toolsai.vscode-ai-0.1.9\out\src\configurations\linuxVM\linuxVMJobService.js:150:24)
	at <anonymous>
	at process._tickCallback (internal/process/next_tick.js:109:7)","level":"error","message":"Unexpected end of JSON input","timestamp":"2018-07-13T02:20:57.641Z"}
{"meta":"/data/job/list?cache=1&refresh=false","stack":"Error: Can not parse list job result
	at LinuxVMJobService.getJobList (C:\Users\Davidham3\.vscode\extensions\ms-toolsai.vscode-ai-0.1.9\out\src\configurations\linuxVM\linuxVMJobService.js:155:19)
	at <anonymous>
	at process._tickCallback (internal/process/next_tick.js:109:7)","level":"error","message":"Can not parse list job result","timestamp":"2018-07-13T02:20:57.644Z"}
{"meta":"","stack":"SyntaxError: Unexpected end of JSON input
	at JSON.parse (<anonymous>)
	at LinuxVMJobService.getJobList (C:\Users\Davidham3\.vscode\extensions\ms-toolsai.vscode-ai-0.1.9\out\src\configurations\linuxVM\linuxVMJobService.js:150:24)
	at <anonymous>
	at process._tickCallback (internal/process/next_tick.js:109:7)","level":"error","message":"Unexpected end of JSON input","timestamp":"2018-07-13T02:21:19.929Z"}
{"meta":"/data/job/list?cache=1&refresh=false","stack":"Error: Can not parse list job result
	at LinuxVMJobService.getJobList (C:\Users\Davidham3\.vscode\extensions\ms-toolsai.vscode-ai-0.1.9\out\src\configurations\linuxVM\linuxVMJobService.js:155:19)
	at <anonymous>
	at process._tickCallback (internal/process/next_tick.js:109:7)","level":"error","message":"Can not parse list job result","timestamp":"2018-07-13T02:21:19.930Z"}
{"meta":"","stack":"SyntaxError: Unexpected end of JSON input
	at JSON.parse (<anonymous>)
	at LinuxVMJobService.getJobList (C:\Users\Davidham3\.vscode\extensions\ms-toolsai.vscode-ai-0.1.9\out\src\configurations\linuxVM\linuxVMJobService.js:150:24)
	at <anonymous>
	at process._tickCallback (internal/process/next_tick.js:109:7)","level":"error","message":"Unexpected end of JSON input","timestamp":"2018-07-13T02:21:21.598Z"}
{"meta":"/data/job/list?cache=1&refresh=true","stack":"Error: Can not parse list job result
	at LinuxVMJobService.getJobList (C:\Users\Davidham3\.vscode\extensions\ms-toolsai.vscode-ai-0.1.9\out\src\configurations\linuxVM\linuxVMJobService.js:155:19)
	at <anonymous>
	at process._tickCallback (internal/process/next_tick.js:109:7)","level":"error","message":"Can not parse list job result","timestamp":"2018-07-13T02:21:21.600Z"}
{"meta":"","stack":"SyntaxError: Unexpected end of JSON input
	at JSON.parse (<anonymous>)
	at LinuxVMJobService.getJobList (C:\Users\Davidham3\.vscode\extensions\ms-toolsai.vscode-ai-0.1.9\out\src\configurations\linuxVM\linuxVMJobService.js:150:24)
	at <anonymous>
	at process._tickCallback (internal/process/next_tick.js:109:7)","level":"error","message":"Unexpected end of JSON input","timestamp":"2018-07-13T02:22:04.635Z"}
{"meta":"/data/job/list?cache=1&refresh=false","stack":"Error: Can not parse list job result
	at LinuxVMJobService.getJobList (C:\Users\Davidham3\.vscode\extensions\ms-toolsai.vscode-ai-0.1.9\out\src\configurations\linuxVM\linuxVMJobService.js:155:19)
	at <anonymous>
	at process._tickCallback (internal/process/next_tick.js:109:7)","level":"error","message":"Can not parse list job result","timestamp":"2018-07-13T02:22:04.636Z"}
{"meta":"","stack":"SyntaxError: Unexpected end of JSON input
	at JSON.parse (<anonymous>)
	at LinuxVMJobService.getJobList (C:\Users\Davidham3\.vscode\extensions\ms-toolsai.vscode-ai-0.1.9\out\src\configurations\linuxVM\linuxVMJobService.js:150:24)
	at <anonymous>
	at process._tickCallback (internal/process/next_tick.js:109:7)","level":"error","message":"Unexpected end of JSON input","timestamp":"2018-07-13T02:22:29.409Z"}
{"meta":"/data/job/list?cache=1&refresh=false","stack":"Error: Can not parse list job result
	at LinuxVMJobService.getJobList (C:\Users\Davidham3\.vscode\extensions\ms-toolsai.vscode-ai-0.1.9\out\src\configurations\linuxVM\linuxVMJobService.js:155:19)
	at <anonymous>
	at process._tickCallback (internal/process/next_tick.js:109:7)","level":"error","message":"Can not parse list job result","timestamp":"2018-07-13T02:22:29.410Z"}
{"meta":"","stack":"SyntaxError: Unexpected end of JSON input
	at JSON.parse (<anonymous>)
	at LinuxVMJobService.getJobList (C:\Users\Davidham3\.vscode\extensions\ms-toolsai.vscode-ai-0.1.9\out\src\configurations\linuxVM\linuxVMJobService.js:150:24)
	at <anonymous>
	at process._tickCallback (internal/process/next_tick.js:109:7)","level":"error","message":"Unexpected end of JSON input","timestamp":"2018-07-13T02:22:33.153Z"}
{"meta":"/data/job/list?cache=1&refresh=false","stack":"Error: Can not parse list job result
	at LinuxVMJobService.getJobList (C:\Users\Davidham3\.vscode\extensions\ms-toolsai.vscode-ai-0.1.9\out\src\configurations\linuxVM\linuxVMJobService.js:155:19)
	at <anonymous>
	at process._tickCallback (internal/process/next_tick.js:109:7)","level":"error","message":"Can not parse list job result","timestamp":"2018-07-13T02:22:33.155Z"}
{"meta":"","stack":"SyntaxError: Unexpected end of JSON input
	at JSON.parse (<anonymous>)
	at LinuxVMJobService.getJobList (C:\Users\Davidham3\.vscode\extensions\ms-toolsai.vscode-ai-0.1.9\out\src\configurations\linuxVM\linuxVMJobService.js:150:24)
	at <anonymous>
	at process._tickCallback (internal/process/next_tick.js:109:7)","level":"error","message":"Unexpected end of JSON input","timestamp":"2018-07-13T02:22:35.421Z"}
{"meta":"/data/job/list?cache=1&refresh=true","stack":"Error: Can not parse list job result
	at LinuxVMJobService.getJobList (C:\Users\Davidham3\.vscode\extensions\ms-toolsai.vscode-ai-0.1.9\out\src\configurations\linuxVM\linuxVMJobService.js:155:19)
	at <anonymous>
	at process._tickCallback (internal/process/next_tick.js:109:7)","level":"error","message":"Can not parse list job result","timestamp":"2018-07-13T02:22:35.423Z"}
{"meta":"","stack":"SyntaxError: Unexpected end of JSON input
	at JSON.parse (<anonymous>)
	at LinuxVMJobService.getJobList (C:\Users\Davidham3\.vscode\extensions\ms-toolsai.vscode-ai-0.1.9\out\src\configurations\linuxVM\linuxVMJobService.js:150:24)
	at <anonymous>
	at process._tickCallback (internal/process/next_tick.js:109:7)","level":"error","message":"Unexpected end of JSON input","timestamp":"2018-07-13T02:22:37.677Z"}
{"meta":"/data/job/list?cache=1&refresh=true","stack":"Error: Can not parse list job result
	at LinuxVMJobService.getJobList (C:\Users\Davidham3\.vscode\extensions\ms-toolsai.vscode-ai-0.1.9\out\src\configurations\linuxVM\linuxVMJobService.js:155:19)
	at <anonymous>
	at process._tickCallback (internal/process/next_tick.js:109:7)","level":"error","message":"Can not parse list job result","timestamp":"2018-07-13T02:22:37.679Z"}
{"meta":"","stack":"SyntaxError: Unexpected end of JSON input
	at JSON.parse (<anonymous>)
	at LinuxVMJobService.getJobList (C:\Users\Davidham3\.vscode\extensions\ms-toolsai.vscode-ai-0.1.9\out\src\configurations\linuxVM\linuxVMJobService.js:150:24)
	at <anonymous>
	at process._tickCallback (internal/process/next_tick.js:109:7)","level":"error","message":"Unexpected end of JSON input","timestamp":"2018-07-13T02:22:53.570Z"}
{"meta":"/data/job/list?cache=1&refresh=false","stack":"Error: Can not parse list job result
	at LinuxVMJobService.getJobList (C:\Users\Davidham3\.vscode\extensions\ms-toolsai.vscode-ai-0.1.9\out\src\configurations\linuxVM\linuxVMJobService.js:155:19)
	at <anonymous>
	at process._tickCallback (internal/process/next_tick.js:109:7)","level":"error","message":"Can not parse list job result","timestamp":"2018-07-13T02:22:53.572Z"}
{"meta":"","stack":"SyntaxError: Unexpected end of JSON input
	at JSON.parse (<anonymous>)
	at LinuxVMJobService.getJobList (C:\Users\Davidham3\.vscode\extensions\ms-toolsai.vscode-ai-0.1.9\out\src\configurations\linuxVM\linuxVMJobService.js:150:24)
	at <anonymous>
	at process._tickCallback (internal/process/next_tick.js:109:7)","level":"error","message":"Unexpected end of JSON input","timestamp":"2018-07-13T02:22:55.200Z"}
{"meta":"/data/job/list?cache=1&refresh=true","stack":"Error: Can not parse list job result
	at LinuxVMJobService.getJobList (C:\Users\Davidham3\.vscode\extensions\ms-toolsai.vscode-ai-0.1.9\out\src\configurations\linuxVM\linuxVMJobService.js:155:19)
	at <anonymous>
	at process._tickCallback (internal/process/next_tick.js:109:7)","level":"error","message":"Can not parse list job result","timestamp":"2018-07-13T02:22:55.205Z"}
{"meta":"","stack":"SyntaxError: Unexpected end of JSON input
	at JSON.parse (<anonymous>)
	at LinuxVMJobService.getJobList (C:\Users\Davidham3\.vscode\extensions\ms-toolsai.vscode-ai-0.1.9\out\src\configurations\linuxVM\linuxVMJobService.js:150:24)
	at <anonymous>
	at process._tickCallback (internal/process/next_tick.js:109:7)","level":"error","message":"Unexpected end of JSON input","timestamp":"2018-07-13T02:22:56.411Z"}
{"meta":"/data/job/list?cache=1&refresh=true","stack":"Error: Can not parse list job result
	at LinuxVMJobService.getJobList (C:\Users\Davidham3\.vscode\extensions\ms-toolsai.vscode-ai-0.1.9\out\src\configurations\linuxVM\linuxVMJobService.js:155:19)
	at <anonymous>
	at process._tickCallback (internal/process/next_tick.js:109:7)","level":"error","message":"Can not parse list job result","timestamp":"2018-07-13T02:22:56.412Z"}
{"meta":"","stack":"SyntaxError: Unexpected end of JSON input
	at JSON.parse (<anonymous>)
	at LinuxVMJobService.getJobList (C:\Users\Davidham3\.vscode\extensions\ms-toolsai.vscode-ai-0.1.9\out\src\configurations\linuxVM\linuxVMJobService.js:150:24)
	at <anonymous>
	at process._tickCallback (internal/process/next_tick.js:109:7)","level":"error","message":"Unexpected end of JSON input","timestamp":"2018-07-13T02:22:57.112Z"}
{"meta":"/data/job/list?cache=1&refresh=true","stack":"Error: Can not parse list job result
	at LinuxVMJobService.getJobList (C:\Users\Davidham3\.vscode\extensions\ms-toolsai.vscode-ai-0.1.9\out\src\configurations\linuxVM\linuxVMJobService.js:155:19)
	at <anonymous>
	at process._tickCallback (internal/process/next_tick.js:109:7)","level":"error","message":"Can not parse list job result","timestamp":"2018-07-13T02:22:57.114Z"}
```

Do you know what that mean?

**Comment by greazer** [comment]
This extension has been reconfigured to target scenarios only dealing with Azure Machine Learning.
