### ISSUE TITLE
Tests blocking pipeline because of failures after changes in vscode library

### ISSUE THREAD

**Issue by sevillal** [microsoft/vscode-tools-for-ai#540]
Pipeline failing job example: https://msasg.visualstudio.com/OpenMind%20Studio/_build/results?buildId=11691879&view=results

**Error**
`### VS Code Extension Test Run ###
C:\Users\AMLExtension\Desktop\agent\_work\1\s\node_modules\vscode\bin\test.js:139
Current working directory: C:\Users\AMLExtension\Desktop\agent\_work\1\s
    shared.getContents('https://vscode-update.azurewebsites.net/api/releases/' + (isInsiders ? 'insider/' : 'stable/') + downloadPlatform, null, null, function (error, tagsRaw) {
           ^

TypeError: shared.getContents is not a function
    at getTag (C:\Users\AMLExtension\Desktop\agent\_work\1\s\node_modules\vscode\bin\test.js:139:12)
    at getDownloadUrl (C:\Users\AMLExtension\Desktop\agent\_work\1\s\node_modules\vscode\bin\test.js:129:5)
    at downloadExecutableAndRunTests (C:\Users\AMLExtension\Desktop\agent\_work\1\s\node_modules\vscode\bin\test.js:97:5)
    at C:\Users\AMLExtension\Desktop\agent\_work\1\s\node_modules\vscode\bin\test.js:156:9
    at suppressedCallback (fs.js:199:5)
    at FSReqWrap.args [as oncomplete] (fs.js:140:20)
`

**Cause**
There where change recently on the vscode-extension-vscode npm package:
https://github.com/microsoft/vscode-extension-vscode/commit/e55dfe8dd080c3c72ee694a1c7c49dc62bd1b5db

**Note**: The npm package also recommends moving to @types/vscode and vscode-test instead @see [Issue#541](https://github.com/microsoft/vscode-tools-for-ai/issues/541)

**Comment by sevillal** [comment]
Merged to "data" feature branch.
